In [ ]:
d={"name": "혼자 공부하는 파이썬"} #JSON 형식은 키와 값에 큰따옴표를 사용함
print(d['name']) #파이썬은 둘 다 사용 가능

혼자 공부하는 파이썬

In [ ]:
#json 패키지를 활용해 d를 JSON 형식에 맞는 문자열로 바꾸기
import json

In [ ]:
#PYTHON -> JSON, json.dumps()함수 사용
#웹 기반 API는 전송하려는 파이썬 객체를 JSON 문자열로 변환하여 전송함
d_str = json.dumps(d, ensure_ascii=False) #'ensure_ascii=False' = 한글이 포함되어있는 d를 원래 저장된 문자로 볼 수 있게 하기 위해서 사용함
print(d_str)

{"name": "혼자 공부하는 파이썬"}

In [ ]:
print(type(d_str))

<class 'str'>

In [ ]:
#JSON -> PYHTON, json.loads()함수 사용
#JSON 문자열을 다시 파이썬 프로그램에 쓰려면 딕셔너리로 바꿔야함
d2 = json.loads(d_str)
print(d2['name'])

혼자 공부하는 파이썬

In [ ]:
print(type(d2))

<class 'dict'>

In [ ]:
d3 = json.loads('{"name": "혼자 공부하는 파이썬", "author":"박해선", "year":2022}')

print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 파이썬
박해선
2022

In [ ]:
print(type(d3))

<class 'dict'>

In [ ]:
d3 = json.loads('{"name": "혼자 공부하는 파이썬", "author":["박해선","홍길동"], "year":2022}')
print(d3['author'][1])

홍길동

In [ ]:
d4_str = """
[
  {"name": "혼자 공부하는 파이썬", "author": "박해선", "year":2022},
  {"name": "혼자 공부하는 머신러닝", "author":"박해선", "year": 2020}
]
"""
d4 = json.loads(d4_str)
print(d4[1]['name'])

혼자 공부하는 머신러닝

In [ ]:
#JSON 문자열 -> 데이터프레임으로 변환, <방법1. read_json()함수>
from io import StringIO #io(입출력 전용 도구상자), StingIO(진짜 파일인 것처럼 랩핑해줌)
import pandas as pd
pd.read_json(StringIO(d4_str))

           name author  year
0   혼자 공부하는 파이썬    박해선  2022
1  혼자 공부하는 머신러닝    박해선  2020

In [ ]:
#<방법2. JSON 문자열을 파이썬 객체로 만든 후 DataFrame 클래스를 사용
pd.DataFrame(d4)

           name author  year
0   혼자 공부하는 파이썬    박해선  2022
1  혼자 공부하는 머신러닝    박해선  2020

In [ ]:
#XML 문자열 -> 파이썬 객체로 변환, fromstring() 함수
x_str = """
<book>
  <name>혼자 공부하는 파이썬</name>
  <author>박해선</author>
  <year>2022</year>
</book>
"""

In [ ]:
#fromstring()함수가 반환하는 객체는 ElementTree 모듈 아래 정의된 Element 클래스의 객체임
import xml.etree.ElementTree as et
book = et.fromstring(x_str)

In [ ]:
print(type(book))

<class 'xml.etree.ElementTree.Element'>

In [ ]:
print(book.tag) #book 객체의 tag 속성을 출력하면 엘리먼트 이름을 확인할 수 있음

book

In [ ]:
#자식 엘리먼트 확인
book_childs = list(book) #list로 변환
print(book_childs)

[<Element 'name' at 0x789111e5fce0>, <Element 'author' at 0x789111e5fd30>, <Element 'year' at 0x789111e5fdd0>]

In [ ]:
#book_childs 변수에 각 항목을 할당하고 text 속성으로 엘리먼트에 있는 텍스트를 출력(순서를 보장하진 않음)
name, author, year = book_childs
print(name.text)
print(author.text)
print(year.text)

혼자 공부하는 파이썬
박해선
2022

In [ ]:
#findtext() 메서드 -> 해당하는 자식 엘리먼트를 탐색하여 자동으로 텍스트를 반환(자식 엘리먼트의 순서가 어떻든 상관없음)
name = book.findtext('name')
author = book.findtext('author')
year = book.findtext('year')
print(name)
print(author)
print(year)

혼자 공부하는 파이썬
박해선
2022

In [ ]:
#자식 엘리먼트가 중복일 때는 부모 엘리먼트를 복수형으로 써주는걸 권장
x2_str = """
<books>
  <book>
    <name>혼자 공부하는 파이썬</name>
    <author>박해선</author>
    <year>2022</year>
  </book>

  <book>
    <name>혼자 공부하는 머신러닝</name>
    <author>박해선</author>
    <year>2020</year>
  </book>

</books>
"""

In [ ]:
import xml.etree.ElementTree as et

books = et.fromstring(x2_str)
print(books.tag)

books

In [ ]:
#여러 개의 자식 엘리먼트 확인하기, findall() 메서드와 for문
#동일한 이름을 가진 여러 개의 자식 엘리먼트를 찾을 때는 findall()메서드와 for문을 함께 사용하면 편함ㄴㄴ
for book in books.findall('book'):
  name = book.findtext('name')
  author = book.findtext('author')
  year = book.findtext('year')
  print(name)
  print(author)
  print(year)
  print()

혼자 공부하는 파이썬
박해선
2022

혼자 공부하는 머신러닝
박해선
2020

In [ ]:
#파이썬에서 URL을 호출하여 데이터를 받는 방법
import requests

In [ ]:
#json 문자열로 받을거기 때문에 XML로 주어지는 API를 format=json 해줘야함
url = 'http://data4library.kr/api/loanItemSrch?format=json&authKey=676df639bfa467fd42811f2635dd142a795b83504ad17e04a5f6cde297e2a1f2&startDt=2026-01-21&endDt=2026-01-23&gender=1&age=20&region=11;31&addCode=0&kdc=6&pageNo=1&pageSize=10'

In [ ]:
#해당 URL은 HTTP GET 방식으로 파라미터 값을 전달하기 때문에 URL을 requests.get()함수에 전달함
r = requests.get(url)

In [ ]:
data=r.json()
print(data)

{'response': {'request': {'region': '11;31', 'startDt': '2026-01-21', 'endDt': '2026-01-23', 'gender': '1', 'age': '20', 'addCode': '0', 'kdc': '6', 'pageNo': 1, 'pageSize': 10, 'format': 'json'}, 'resultNum': 10, 'numFound': 277, 'docs': [{'doc': {'no': 1, 'ranking': '1', 'bookname': '모국어는 차라리 침묵 :목정원 산문 ', 'authors': '지은이: 목정원', 'publisher': '아침달', 'publication_year': '2021', 'isbn13': '9791189467302', 'addition_symbol': '03600', 'vol': '', 'class_no': '600.04', 'class_nm': '예술 > 예술 > 예술', 'bookImageURL': 'https://image.aladin.co.kr/product/28091/4/cover/k062734948_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=6315295', 'loan_count': '5'}}, {'doc': {'no': 2, 'ranking': '2', 'bookname': '디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말 ', 'authors': '테오 잉글리스 지음 ;이희수 옮김', 'publisher': '윌북', 'publication_year': '2025', 'isbn13': '9791155818503', 'addition_symbol': '03650', 'vol': '', 'class_no': '658.3', 'class_nm': '예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터', 'bookImageURL': 'https://image.aladin.co.kr/product/36973/10/cover200/k682030823_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=7110820', 'loan_count': '4'}}, {'doc': {'no': 3, 'ranking': '3', 'bookname': '당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임 ', 'authors': '글: 모데스토 가르시아 ;번역: 엄지영', 'publisher': '중앙일보에스', 'publication_year': '2022', 'isbn13': '9788927812975', 'addition_symbol': '03030', 'vol': '', 'class_no': '691.9', 'class_nm': '예술 > 오락, 운동 > 오락', 'bookImageURL': 'https://image.aladin.co.kr/product/29623/60/cover/8927812972_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=6479562', 'loan_count': '3'}}, {'doc': {'no': 4, 'ranking': '3', 'bookname': '다른 방식으로 보기 ', 'authors': '존 버거 [지음] ;최민 옮김', 'publisher': '열화당', 'publication_year': '2012', 'isbn13': '9788930104272', 'addition_symbol': '03840', 'vol': '', 'class_no': '604', 'class_nm': '예술 > 예술 > 미술의 주제', 'bookImageURL': 'http://image.aladin.co.kr/product/1875/91/cover/8930104274_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1864587', 'loan_count': '3'}}, {'doc': {'no': 5, 'ranking': '3', 'bookname': "디자인 구구단 =디자인이 필요한 순간, '툭' 튀어나오는 디자인 공식 /9 basic elements of design ", 'authors': '지은이: 에이핫', 'publisher': '길벗', 'publication_year': '2024', 'isbn13': '9791140714063', 'addition_symbol': '03000', 'vol': '', 'class_no': '658', 'class_nm': '예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터', 'bookImageURL': 'https://image.aladin.co.kr/product/34360/88/cover200/k182932901_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=6922110', 'loan_count': '3'}}, {'doc': {'no': 6, 'ranking': '3', 'bookname': '열심히 대충 쓰는 사람 :브로콜리너마저 덕원의 가사, 노래, 글을 짓는 마음가짐 ', 'authors': '윤덕원 지음', 'publisher': '세미콜론', 'publication_year': '2025', 'isbn13': '9791194087755', 'addition_symbol': '03810', 'vol': '', 'class_no': '673.51104', 'class_nm': '예술 > 음악 > 성악', 'bookImageURL': 'https://image.aladin.co.kr/product/37039/53/cover200/k262030030_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=7143463', 'loan_count': '3'}}, {'doc': {'no': 7, 'ranking': '7', 'bookname': '드라마 만드는 사람 :찾고, 조율하고, 완성하는 기획 PD의 세계 ', 'authors': '송진선 지음', 'publisher': 'RHK(알에이치코리아)', 'publication_year': '2025', 'isbn13': '9788925572970', 'addition_symbol': '03680', 'vol': '', 'class_no': '687.15', 'class_nm': '예술 > 연극 > 텔레비젼극', 'bookImageURL': 'https://image.aladin.co.kr/product/37516/44/cover200/8925572974_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=7169471', 'loan_count': '2'}}, {'doc': {'no': 8, 'ranking': '7', 'bookname': '당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임 ', 'authors': '글: 모데스토 가르시아 ;번역: 엄지영', 'publisher': '중앙일보에스', 'publication_year': '2025', 'isbn13': '9788927813361', 'addition_symbol': '03030', 'vol': '3', 'class_no': '691.9', 'class_nm': '예술 > 오락, 운동 > 오락', 'bookImageURL': 'https://image.aladin.co.kr/product/36383/60/cover200/8927813367_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=7059517', 'loan_count': '2'}}, {'doc': {'no': 9, 'ranking': '7', 'bookname': '창작수업 ', 'authors': '지은이: 변영주', 'publisher': '창비', 'publication_year': '2024', 'isbn13': '9788936480264', 'addition_symbol': '03300', 'vol': '', 'class_no': '688.13', 'class_nm': '예술 > 연극 > 영화', 'bookImageURL': 'https://image.aladin.co.kr/product/34289/27/cover200/893648026x_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=6916630', 'loan_count': '2'}}, {'doc': {'no': 10, 'ranking': '7', 'bookname': '나의 문구 여행기 :좋아하는 것을 좋아하는 용기에 대하여 ', 'authors': '지은이: 문경연 ;사진: 한진희', 'publisher': '뜨인돌', 'publication_year': '2020', 'isbn13': '9788958077466', 'addition_symbol': '03810', 'vol': '', 'class_no': '649', 'class_nm': '예술 > 서예 > 문방구', 'bookImageURL': 'https://image.aladin.co.kr/product/22693/84/cover/8958077468_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5580162', 'loan_count': '2'}}]}}

In [ ]:
#코랩이나 주피터 노트북은 print()함수를 사용하지 않아도 코드 셀의 마지막 라인의 실행 결과를 자동으로 출력해줌
data

{'response': {'request': {'region': '11;31',
   'startDt': '2026-01-21',
   'endDt': '2026-01-23',
   'gender': '1',
   'age': '20',
   'addCode': '0',
   'kdc': '6',
   'pageNo': 1,
   'pageSize': 10,
   'format': 'json'},
  'resultNum': 10,
  'numFound': 277,
  'docs': [{'doc': {'no': 1,
     'ranking': '1',
     'bookname': '모국어는 차라리 침묵 :목정원 산문 ',
     'authors': '지은이: 목정원',
     'publisher': '아침달',
     'publication_year': '2021',
     'isbn13': '9791189467302',
     'addition_symbol': '03600',
     'vol': '',
     'class_no': '600.04',
     'class_nm': '예술 > 예술 > 예술',
     'bookImageURL': 'https://image.aladin.co.kr/product/28091/4/cover/k062734948_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=6315295',
     'loan_count': '5'}},
   {'doc': {'no': 2,
     'ranking': '2',
     'bookname': '디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말 ',
     'authors': '테오 잉글리스 지음 ;이희수 옮김',
     'publisher': '윌북',
     'publication_year': '2025',
     'isbn13': '9791155818503',
     'addition_symbol': '03650',
     'vol': '',
     'class_no': '658.3',
     'class_nm': '예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터',
     'bookImageURL': 'https://image.aladin.co.kr/product/36973/10/cover200/k682030823_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=7110820',
     'loan_count': '4'}},
   {'doc': {'no': 3,
     'ranking': '3',
     'bookname': '당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임 ',
     'authors': '글: 모데스토 가르시아 ;번역: 엄지영',
     'publisher': '중앙일보에스',
     'publication_year': '2022',
     'isbn13': '9788927812975',
     'addition_symbol': '03030',
     'vol': '',
     'class_no': '691.9',
     'class_nm': '예술 > 오락, 운동 > 오락',
     'bookImageURL': 'https://image.aladin.co.kr/product/29623/60/cover/8927812972_2.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=6479562',
     'loan_count': '3'}},
   {'doc': {'no': 4,
     'ranking': '3',
     'bookname': '다른 방식으로 보기 ',
     'authors': '존 버거 [지음] ;최민 옮김',
     'publisher': '열화당',
     'publication_year': '2012',
     'isbn13': '9788930104272',
     'addition_symbol': '03840',
     'vol': '',
     'class_no': '604',
     'class_nm': '예술 > 예술 > 미술의 주제',
     'bookImageURL': 'http://image.aladin.co.kr/product/1875/91/cover/8930104274_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=1864587',
     'loan_count': '3'}},
   {'doc': {'no': 5,
     'ranking': '3',
     'bookname': "디자인 구구단 =디자인이 필요한 순간, '툭' 튀어나오는 디자인 공식 /9 basic elements of design ",
     'authors': '지은이: 에이핫',
     'publisher': '길벗',
     'publication_year': '2024',
     'isbn13': '9791140714063',
     'addition_symbol': '03000',
     'vol': '',
     'class_no': '658',
     'class_nm': '예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터',
     'bookImageURL': 'https://image.aladin.co.kr/product/34360/88/cover200/k182932901_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=6922110',
     'loan_count': '3'}},
   {'doc': {'no': 6,
     'ranking': '3',
     'bookname': '열심히 대충 쓰는 사람 :브로콜리너마저 덕원의 가사, 노래, 글을 짓는 마음가짐 ',
     'authors': '윤덕원 지음',
     'publisher': '세미콜론',
     'publication_year': '2025',
     'isbn13': '9791194087755',
     'addition_symbol': '03810',
     'vol': '',
     'class_no': '673.51104',
     'class_nm': '예술 > 음악 > 성악',
     'bookImageURL': 'https://image.aladin.co.kr/product/37039/53/cover200/k262030030_2.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=7143463',
     'loan_count': '3'}},
   {'doc': {'no': 7,
     'ranking': '7',
     'bookname': '드라마 만드는 사람 :찾고, 조율하고, 완성하는 기획 PD의 세계 ',
     'authors': '송진선 지음',
     'publisher': 'RHK(알에이치코리아)',
     'publication_year': '2025',
     'isbn13': '9788925572970',
     'addition_symbol': '03680',
     'vol': '',
     'class_no': '687.15',
     'class_nm': '예술 > 연극 > 텔레비젼극',
     'bookImageURL': 'https://image.aladin.co.kr/product/37516/44/cover200/8925572974_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=7169471',
     'loan_count': '2'}},
   {'doc': {'no': 8,
     'ranking': '7',
     'bookname': '당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임 ',
     'authors': '글: 모데스토 가르시아 ;번역: 엄지영',
     'publisher': '중앙일보에스',
     'publication_year': '2025',
     'isbn13': '9788927813361',
     'addition_symbol': '03030',
     'vol': '3',
     'class_no': '691.9',
     'class_nm': '예술 > 오락, 운동 > 오락',
     'bookImageURL': 'https://image.aladin.co.kr/product/36383/60/cover200/8927813367_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=7059517',
     'loan_count': '2'}},
   {'doc': {'no': 9,
     'ranking': '7',
     'bookname': '창작수업 ',
     'authors': '지은이: 변영주',
     'publisher': '창비',
     'publication_year': '2024',
     'isbn13': '9788936480264',
     'addition_symbol': '03300',
     'vol': '',
     'class_no': '688.13',
     'class_nm': '예술 > 연극 > 영화',
     'bookImageURL': 'https://image.aladin.co.kr/product/34289/27/cover200/893648026x_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=6916630',
     'loan_count': '2'}},
   {'doc': {'no': 10,
     'ranking': '7',
     'bookname': '나의 문구 여행기 :좋아하는 것을 좋아하는 용기에 대하여 ',
     'authors': '지은이: 문경연 ;사진: 한진희',
     'publisher': '뜨인돌',
     'publication_year': '2020',
     'isbn13': '9788958077466',
     'addition_symbol': '03810',
     'vol': '',
     'class_no': '649',
     'class_nm': '예술 > 서예 > 문방구',
     'bookImageURL': 'https://image.aladin.co.kr/product/22693/84/cover/8958077468_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5580162',
     'loan_count': '2'}}]}}

In [ ]:
#response, docs에 매핑된 리스트를 순회하면서 doc 키에 매핑된 딕셔너리를 추출한 후 빈 리스트에 추가(for문 활용)
books=[]
for d in data['response']['docs']:
  books.append(d['doc'])

In [ ]:
books

[{'no': 1,
  'ranking': '1',
  'bookname': '모국어는 차라리 침묵 :목정원 산문 ',
  'authors': '지은이: 목정원',
  'publisher': '아침달',
  'publication_year': '2021',
  'isbn13': '9791189467302',
  'addition_symbol': '03600',
  'vol': '',
  'class_no': '600.04',
  'class_nm': '예술 > 예술 > 예술',
  'bookImageURL': 'https://image.aladin.co.kr/product/28091/4/cover/k062734948_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=6315295',
  'loan_count': '5'},
 {'no': 2,
  'ranking': '2',
  'bookname': '디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말 ',
  'authors': '테오 잉글리스 지음 ;이희수 옮김',
  'publisher': '윌북',
  'publication_year': '2025',
  'isbn13': '9791155818503',
  'addition_symbol': '03650',
  'vol': '',
  'class_no': '658.3',
  'class_nm': '예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터',
  'bookImageURL': 'https://image.aladin.co.kr/product/36973/10/cover200/k682030823_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=7110820',
  'loan_count': '4'},
 {'no': 3,
  'ranking': '3',
  'bookname': '당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임 ',
  'authors': '글: 모데스토 가르시아 ;번역: 엄지영',
  'publisher': '중앙일보에스',
  'publication_year': '2022',
  'isbn13': '9788927812975',
  'addition_symbol': '03030',
  'vol': '',
  'class_no': '691.9',
  'class_nm': '예술 > 오락, 운동 > 오락',
  'bookImageURL': 'https://image.aladin.co.kr/product/29623/60/cover/8927812972_2.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=6479562',
  'loan_count': '3'},
 {'no': 4,
  'ranking': '3',
  'bookname': '다른 방식으로 보기 ',
  'authors': '존 버거 [지음] ;최민 옮김',
  'publisher': '열화당',
  'publication_year': '2012',
  'isbn13': '9788930104272',
  'addition_symbol': '03840',
  'vol': '',
  'class_no': '604',
  'class_nm': '예술 > 예술 > 미술의 주제',
  'bookImageURL': 'http://image.aladin.co.kr/product/1875/91/cover/8930104274_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=1864587',
  'loan_count': '3'},
 {'no': 5,
  'ranking': '3',
  'bookname': "디자인 구구단 =디자인이 필요한 순간, '툭' 튀어나오는 디자인 공식 /9 basic elements of design ",
  'authors': '지은이: 에이핫',
  'publisher': '길벗',
  'publication_year': '2024',
  'isbn13': '9791140714063',
  'addition_symbol': '03000',
  'vol': '',
  'class_no': '658',
  'class_nm': '예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터',
  'bookImageURL': 'https://image.aladin.co.kr/product/34360/88/cover200/k182932901_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=6922110',
  'loan_count': '3'},
 {'no': 6,
  'ranking': '3',
  'bookname': '열심히 대충 쓰는 사람 :브로콜리너마저 덕원의 가사, 노래, 글을 짓는 마음가짐 ',
  'authors': '윤덕원 지음',
  'publisher': '세미콜론',
  'publication_year': '2025',
  'isbn13': '9791194087755',
  'addition_symbol': '03810',
  'vol': '',
  'class_no': '673.51104',
  'class_nm': '예술 > 음악 > 성악',
  'bookImageURL': 'https://image.aladin.co.kr/product/37039/53/cover200/k262030030_2.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=7143463',
  'loan_count': '3'},
 {'no': 7,
  'ranking': '7',
  'bookname': '드라마 만드는 사람 :찾고, 조율하고, 완성하는 기획 PD의 세계 ',
  'authors': '송진선 지음',
  'publisher': 'RHK(알에이치코리아)',
  'publication_year': '2025',
  'isbn13': '9788925572970',
  'addition_symbol': '03680',
  'vol': '',
  'class_no': '687.15',
  'class_nm': '예술 > 연극 > 텔레비젼극',
  'bookImageURL': 'https://image.aladin.co.kr/product/37516/44/cover200/8925572974_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=7169471',
  'loan_count': '2'},
 {'no': 8,
  'ranking': '7',
  'bookname': '당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임 ',
  'authors': '글: 모데스토 가르시아 ;번역: 엄지영',
  'publisher': '중앙일보에스',
  'publication_year': '2025',
  'isbn13': '9788927813361',
  'addition_symbol': '03030',
  'vol': '3',
  'class_no': '691.9',
  'class_nm': '예술 > 오락, 운동 > 오락',
  'bookImageURL': 'https://image.aladin.co.kr/product/36383/60/cover200/8927813367_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=7059517',
  'loan_count': '2'},
 {'no': 9,
  'ranking': '7',
  'bookname': '창작수업 ',
  'authors': '지은이: 변영주',
  'publisher': '창비',
  'publication_year': '2024',
  'isbn13': '9788936480264',
  'addition_symbol': '03300',
  'vol': '',
  'class_no': '688.13',
  'class_nm': '예술 > 연극 > 영화',
  'bookImageURL': 'https://image.aladin.co.kr/product/34289/27/cover200/893648026x_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=6916630',
  'loan_count': '2'},
 {'no': 10,
  'ranking': '7',
  'bookname': '나의 문구 여행기 :좋아하는 것을 좋아하는 용기에 대하여 ',
  'authors': '지은이: 문경연 ;사진: 한진희',
  'publisher': '뜨인돌',
  'publication_year': '2020',
  'isbn13': '9788958077466',
  'addition_symbol': '03810',
  'vol': '',
  'class_no': '649',
  'class_nm': '예술 > 서예 > 문방구',
  'bookImageURL': 'https://image.aladin.co.kr/product/22693/84/cover/8958077468_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5580162',
  'loan_count': '2'}]

In [ ]:
import pandas as pd

In [ ]:
books_df = pd.DataFrame(books)
books_df

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,bookImageURL,bookDtlUrl,loan_count
0,1,1,모국어는 차라리 침묵 :목정원 산문,지은이: 목정원,아침달,2021,9791189467302,03600,,600.04,예술 > 예술 > 예술,https://image.aladin.co.kr/product/28091/4/cov...,https://data4library.kr/bookV?seq=6315295,5
1,2,2,디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말,테오 잉글리스 지음 ;이희수 옮김,윌북,2025,9791155818503,03650,,658.3,"예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터",https://image.aladin.co.kr/product/36973/10/co...,https://data4library.kr/bookV?seq=7110820,4
2,3,3,당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임,글: 모데스토 가르시아 ;번역: 엄지영,중앙일보에스,2022,9788927812975,03030,,691.9,"예술 > 오락, 운동 > 오락",https://image.aladin.co.kr/product/29623/60/co...,https://data4library.kr/bookV?seq=6479562,3
3,4,3,다른 방식으로 보기,존 버거 [지음] ;최민 옮김,열화당,2012,9788930104272,03840,,604,예술 > 예술 > 미술의 주제,http://image.aladin.co.kr/product/1875/91/cove...,https://data4library.kr/bookV?seq=1864587,3
4,5,3,"디자인 구구단 =디자인이 필요한 순간, '툭' 튀어나오는 디자인 공식 /9 basi...",지은이: 에이핫,길벗,2024,9791140714063,03000,,658,"예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터",https://image.aladin.co.kr/product/34360/88/co...,https://data4library.kr/bookV?seq=6922110,3
5,6,3,"열심히 대충 쓰는 사람 :브로콜리너마저 덕원의 가사, 노래, 글을 짓는 마음가짐",윤덕원 지음,세미콜론,2025,9791194087755,03810,,673.51104,예술 > 음악 > 성악,https://image.aladin.co.kr/product/37039/53/co...,https://data4library.kr/bookV?seq=7143463,3
6,7,7,"드라마 만드는 사람 :찾고, 조율하고, 완성하는 기획 PD의 세계",송진선 지음,RHK(알에이치코리아),2025,9788925572970,03680,,687.15,예술 > 연극 > 텔레비젼극,https://image.aladin.co.kr/product/37516/44/co...,https://data4library.kr/bookV?seq=7169471,2
7,8,7,당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임,글: 모데스토 가르시아 ;번역: 엄지영,중앙일보에스,2025,9788927813361,03030,3,691.9,"예술 > 오락, 운동 > 오락",https://image.aladin.co.kr/product/36383/60/co...,https://data4library.kr/bookV?seq=7059517,2
8,9,7,창작수업,지은이: 변영주,창비,2024,9788936480264,03300,,688.13,예술 > 연극 > 영화,https://image.aladin.co.kr/product/34289/27/co...,https://data4library.kr/bookV?seq=6916630,2
9,10,7,나의 문구 여행기 :좋아하는 것을 좋아하는 용기에 대하여,지은이: 문경연 ;사진: 한진희,뜨인돌,2020,9788958077466,03810,,649,예술 > 서예 > 문방구,https://image.aladin.co.kr/product/22693/84/co...,https://data4library.kr/bookV?seq=5580162,2

In [ ]:
#JSON 파일로 저장해주는 메서드, to_json() 메서드
books_df.to_json('20s_best_book.json')

In [ ]:
#리스트 내포 설명(for문을 대괄호로 감싸서 리스트로 만드는 방법)
#예시1
#기존 for문
squares = []
for x in range(1, 6):
    squares.append(x**2)

print(squares)  # [1, 4, 9, 16, 25]

#리스트 내포
squares = [x**2 for x in range(1, 6)]

print(squares)  # [1, 4, 9, 16, 25]

#------------------------------------------------------------------------------------------

#예시2
#기존 for문 & if문
evens = []
for x in range(1, 11):
    if x % 2 == 0:
        evens.append(x**2)

# 리스트 내포
evens = [x**2 for x in range(1, 11) if x % 2 == 0]

print(evens)  # [4, 16, 36, 64, 100]

##<정리>
#### -JSON & XML 구조

*   JSON - 데이터 전달 포맷.HTML&XML보다 사람이 읽기 편하고 간단하게 파이썬 객체로 변환 가능
*   XML - 파이썬에서는 기본으로 제공되는 xml 패키지를 사용하여 XML 문서에 있는 엘리먼트를 탐색할 수 있음. 판다스의 경우 read_xml() 할수를 사용하여 데이터프레임으로 바꿀 수 있음.

#### -requests 패키지를 활용해 필요한 공개 API를 찾아서 파이썬 프로그램에서 호출하고 데이터 프레임으로 변환하는 과정을 자동화함
#### -requests 패키지의 get()함수를 사용해 API 주소로 데이터를 받음
#### -json() 메서드를 사용해 파이썬 객체로 변환함