##웹 스크래핑(웹 크롤링)?
-> 프로그램으로 웹사이트의 페이지를 옮겨 가면서 데이터를 추출하는 작업

In [ ]:
import pandas as pd
import json
import gdown
gdown.download('http://drive.google.com/uc?id=10CnAwxTDCfYp-aH3ULyJ1LiO6GZK0SC8','20s_best_book.json',quiet=False)

Downloading...
From: http://drive.google.com/uc?id=10CnAwxTDCfYp-aH3ULyJ1LiO6GZK0SC8
To: /content/20s_best_book.json
100%|██████████| 5.44k/5.44k [00:00<00:00, 14.3MB/s]

'20s_best_book.json'

In [ ]:
#read_json()함수 -> JSON 데이터를 DF으로 가져옴 & head() 메서드로 처음 다섯 개 행을 출력함
books_df = pd.read_json('20s_best_book.json')
books_df.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,bookImageURL,bookDtlUrl,loan_count
0,1,1,모국어는 차라리 침묵 :목정원 산문,지은이: 목정원,아침달,2021,9791189467302,3600,,600.04,예술 > 예술 > 예술,https://image.aladin.co.kr/product/28091/4/cov...,https://data4library.kr/bookV?seq=6315295,5
1,2,2,디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말,테오 잉글리스 지음 ;이희수 옮김,윌북,2025,9791155818503,3650,,658.30,"예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터",https://image.aladin.co.kr/product/36973/10/co...,https://data4library.kr/bookV?seq=7110820,4
2,3,3,당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임,글: 모데스토 가르시아 ;번역: 엄지영,중앙일보에스,2022,9788927812975,3030,,691.90,"예술 > 오락, 운동 > 오락",https://image.aladin.co.kr/product/29623/60/co...,https://data4library.kr/bookV?seq=6479562,3
3,4,3,다른 방식으로 보기,존 버거 [지음] ;최민 옮김,열화당,2012,9788930104272,3840,,604.00,예술 > 예술 > 미술의 주제,http://image.aladin.co.kr/product/1875/91/cove...,https://data4library.kr/bookV?seq=1864587,3
4,5,3,"디자인 구구단 =디자인이 필요한 순간, '툭' 튀어나오는 디자인 공식 /9 basi...",지은이: 에이핫,길벗,2024,9791140714063,3000,,658.00,"예술 > 회화, 도화 > 그래픽디자인, 도안, 포스터",https://image.aladin.co.kr/product/34360/88/co...,https://data4library.kr/bookV?seq=6922110,3

In [ ]:
#데이터프레임에서 특정 열만 선택하기
#방법 1. 원하는 열 이름을 리스트로 만들어 df의 인덱스처럼 사용하면 됨
books = books_df[['no','ranking','bookname','authors','publisher','publication_year','isbn13']]
books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,모국어는 차라리 침묵 :목정원 산문,지은이: 목정원,아침달,2021,9791189467302
1,2,2,디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말,테오 잉글리스 지음 ;이희수 옮김,윌북,2025,9791155818503
2,3,3,당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임,글: 모데스토 가르시아 ;번역: 엄지영,중앙일보에스,2022,9788927812975
3,4,3,다른 방식으로 보기,존 버거 [지음] ;최민 옮김,열화당,2012,9788930104272
4,5,3,"디자인 구구단 =디자인이 필요한 순간, '툭' 튀어나오는 디자인 공식 /9 basi...",지은이: 에이핫,길벗,2024,9791140714063

In [ ]:
#데이터프레임에서 특정 열만 선택하기
#방법 2. loc() 메서드 사용하기(대괄호를 사용하여 행의 목록과 열의 목록을 받음)
books_df.loc[[0,1],['bookname','authors']]

                           bookname             authors
0              모국어는 차라리 침묵 :목정원 산문             지은이: 목정원
1  디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말   테오 잉글리스 지음 ;이희수 옮김

###추가 개념 : iloc()
iloc 메서드는 인덱스의 위치를 사용함

In [ ]:
#iloc
books_df.iloc[[0,1],[2,3]] #'bookname'과 'authors'는 각각 2열 3열임

                           bookname             authors
0              모국어는 차라리 침묵 :목정원 산문             지은이: 목정원
1  디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말   테오 잉글리스 지음 ;이희수 옮김

In [ ]:
#슬라이스 연산자(:)
books = books_df.loc[:, 'no':'isbn13']
books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,모국어는 차라리 침묵 :목정원 산문,지은이: 목정원,아침달,2021,9791189467302
1,2,2,디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말,테오 잉글리스 지음 ;이희수 옮김,윌북,2025,9791155818503
2,3,3,당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임,글: 모데스토 가르시아 ;번역: 엄지영,중앙일보에스,2022,9788927812975
3,4,3,다른 방식으로 보기,존 버거 [지음] ;최민 옮김,열화당,2012,9788930104272
4,5,3,"디자인 구구단 =디자인이 필요한 순간, '툭' 튀어나오는 디자인 공식 /9 basi...",지은이: 에이핫,길벗,2024,9791140714063

In [ ]:
#step 지정 가능
books_df.loc[::2, 'no':'isbn13'].head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,모국어는 차라리 침묵 :목정원 산문,지은이: 목정원,아침달,2021,9791189467302
2,3,3,당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임,글: 모데스토 가르시아 ;번역: 엄지영,중앙일보에스,2022,9788927812975
4,5,3,"디자인 구구단 =디자인이 필요한 순간, '툭' 튀어나오는 디자인 공식 /9 basi...",지은이: 에이핫,길벗,2024,9791140714063
6,7,7,"드라마 만드는 사람 :찾고, 조율하고, 완성하는 기획 PD의 세계",송진선 지음,RHK(알에이치코리아),2025,9788925572970
8,9,7,창작수업,지은이: 변영주,창비,2024,9788936480264

In [ ]:
#검색 결과 페이지 HTML 가져오기 = requests.get() 함수
import requests
isbn = 9791189467302
url = 'https://www.yes24.com/Product/Search?domain=ALL&query={}'
r = requests.get(url.format(isbn)) #format() 메서드를 사용해 isbn 변수에 저장된 값을 url 변수에 저장함

In [ ]:
print(r.text)

<!DOCTYPE html>
<html lang="ko">
<head>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta http-equiv="Accept-CH" content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" />
    <meta http-equiv="Accept-CH-Lifetime" content="86400" />
    <meta name="referrer" content="unsafe-url" />
    <meta name="viewport" content="width=1170" />
    <title>9791189467302 - 예스24</title>
    <meta name="title" content="예스24" />
    <meta name="description" content="도서, 티켓, 음반, 굿즈, 커뮤니티까지 문화 전반을 아우르는 국내 대표 문화콘텐츠 플랫폼, 아낌없는 혜택과 총알배송을 경험해보세요." />
    <meta name="keywords" content="인터넷 서점, 온라인 쇼핑, 상품 추천, 쇼핑몰, 상품 검색, 도서 정보, 국내도서, 외국도서, 전자책, eBook, 이북, 크레마, 공연, 콘서트, 뮤지컬, 음반, 예매, DVD, 블루레이, 예스24, YES24, 교보문고, 알라딘, 리센스, 예스24 도서용품, 친환경 PB 브랜드, 사은품, 굿즈" />
                                            <link title="YES24" rel="search" type="application/opensearchdescription+xml" href="//www.yes24.com/OpensearchDescription.xml">






<script src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20250613"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20260701"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20260701"></script>
<script src="https://www.yes24.com/Javascript/util.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/yes_header.js?v=20260630"></script>
<script src="https://www.yes24.com/Javascript/hiveSlide.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20260630"></script>
<script src="https://www.yes24.com/Javascript/recentviewgoods.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/bulletSearch.js?v=20260630"></script>
<script src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20250613"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20250613"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20260630"></script>
    <script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.js?v=20260630"></script>
    <script src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20250613"></script>
    <link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20260630" charset=&quot;euc-kr&quot; />
    <link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20260630" />
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
<![endif]-->
<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" type="image/x-icon" rel="shortcut icon" />
<script src="https://www.yes24.com/Javascript/Common.js?v=20260624"></script>
<script src="https://www.yes24.com/Javascript/headerSetting.js?v=20260630"></script>
<script src="https://image.yes24.com/static/logging/clickstream.min.js?v=20260630"></script>
<script>
    var YesData = new function () {
        var _HTTP_URL = "https://www.yes24.com";
        var _NOW_HTTP_URL = "https://www.yes24.com";
        var _BLOG_URL = "https://blog.yes24.com";
        var _IMG_HOST_IMG = "https://image.yes24.com";
        var _IsWelcomePage = "False";
        var _MEM_AGE = 0;
        var _PID = "";
        var _FRONT_API_URL = "https://frontapi.yes24.com";
        var _ParenerInfomagion = {};
        var _IsdevServer = "False";
        var _IsHttps = "True";

        this.HTTP_URL = function () { return _HTTP_URL; }
        this.NOW_HTTP_URL = function () { return _NOW_HTTP_URL; }
        this.BLOG_URL = function () { return _BLOG_URL; }
        this.IMG_HOST_IMG = function () { return _IMG_HOST_IMG; }
        this.IsWelcomePage = function () { return _IsWelcomePage; }
        this.MEM_AGE = function () { return _MEM_AGE; }
        this.PID = function () { return _PID; }
        this.FRONT_API_URL = function() {return _FRONT_API_URL;}
        this.ParenerInfomagion = function () { return _ParenerInfomagion; }
        this.IsdevServer = function () { return _IsdevServer; }
        this.IsHttps = function () { return _IsHttps; }
    }

    var PC_HTTPS_URL = "https://www.yes24.com";
    var bnSkyAdArray = new Array();                 //AD 스카이스크래퍼용
    var HeaderDisplay = "";
    var isMania = "N";
    var recentViewGoods = new RecentViewGoods();    //최근본 상품
    var SearchBarRenderingEnable = true;            //광고창을 계속 불러올지 여부
    var USERNO = "";
    var IS_NATIVE_APPS = false;
    var is_debug = Boolean(0);
    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
    var IsScExpDate = scToday > scExpDate ? false : true;

    // 브레이즈 위한 설정 값
    var TUSERNO = '';
    var isUnder14 = 'False';
    function activeQuickSubmenu(row) {
        var $row = $(row),
            submenuId = $row.attr('data-submenu-id'),
            $submenu = $("#" + submenuId);
        $("#quickCate > li").removeClass("on");
        $submenu.css("display", "block");
        $row.parent().addClass("on");
        if (!quickChkWide) {
            if ((document.compatMode === "CSS1Compat") || (navigator.appName != 'Microsoft Internet Explorer')) {
                $("#quickCateWrap .quickCateLiWrap").css("overflow", "hidden");
                $("#quickCateWrap .quickCateLiWrap").stop().animate({ width: "664px" }, 200, "easeInCubic", function () {
                    if ($('#quickCateWrap').css("display") == "none") {
                        $(this).css("width", "auto");
                    }
                });
            } else {
                $("#quickCateWrap .quickCateLiWrap").css("width", "564px");
            }
            quickChkWide = true;
        }
    }
    function deactiveQuickSubmenu(row) {
        var $row = $(row),
            submenuId = $row.attr('data-submenu-id'),
            $submenu = $("#" + submenuId);
        $submenu.css("display", "none");
        $row.parent().removeClass("on");
    }
    function hideUpperBn() {
        setWcode('001_001');
        var todayDate = new Date();
        setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#upperBnWrap").css("display", "none");
    }
    // 검색어 입력창에 포커스 시
    function SearchBarRenderingEnableSet(enable) {
        //광고 제거
        SearchBarRenderingEnable = enable;
        $("#ulSchScopeOpt").hide();
    }
    // 검색어 입력창 광고 노출
    function fnSearchBarRendering() {
        var seardtext = $('#hdSearchBarText').val();
        var bannerLink = $("#hdSearchBarLink").val();
        $('#query').val(seardtext);
        $('#query').addClass("iptTxt iptTxtAd");
        $('#keywordAd').val(bannerLink);
    }
    //검색창 선택 시
    function showLatestSearchList() {
        SearchBarRenderingEnableSet(false);
        if (String($("input#query").val()).length == 0) {
            try {
                srchHistory.show();
            } catch (e) { }
            $("#suggestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#latestSearchList").show();
        } else {
            BulletSearchRenewal.InitBulletSearch();
            showSuggestSearchList();
        }
    }
    //검색창 포커스 아웃
    function blurSearchBar() {
        var queryValue = $("#query").val();
        if (queryValue == "" || queryValue == null) {
            if (location.href.toLowerCase().indexOf('/product/search') == -1) {
                fnSearchBarRendering();
                query_init = false;
            }
        }
    }
    function hideLatestSearchList() {
        $("#searchKeyLayer").hide();
        $("#latestSearchList").hide();
    }
    //추천검색어
    function showSuggestSearchList() {
        var domainVal = String($("#qdomain").val());
        if (domainVal != '티켓' && domainVal != '블로그' && domainVal != '채널예스' && domainVal != 'STORE' && domainVal != 'UsedGoods') {
            $("#latestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#suggestSearchList").show();
        } else {
            $("#suggestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#latestSearchList").show();
        }
    }
    function hideSuggestSearchList() {
        $("#searchKeyLayer").hide();
        $("#suggestSearchList").hide();
    }
    function closePartnerBn(close) {
        $("#bnPartnerWing").css({ "display": "none" });
        setCookie("Yes24_PartnerWingRightArea", "OK", 1);
    }
    function setCookiePartnerWingBn() {
        var name = "PartnerWingArea";
        var value = "OK";
        var expiredays = 1;
        var todayDate = new Date();
        todayDate.setDate(todayDate.getDate() + expiredays);
        document.cookie = name + "=" + escape(value) + "; path=/; expires=" + todayDate.toGMTString() + "; domain=.yes24.com;"
        closePartnerBn();
    }
    function OAS_RICHTest() {
        try {
            if (OAS_RICH.toString().indexOf("//adgirl.yes24.com/RealMedia/ads/Creatives/default/empty.gif") <= 0) {
                if (getCookie("Yes24_PartnerWingRightArea") != "OK") {
                    /*OAS_RICH("Right");*/
                    $("#bnPartnerWing a").eq(1).addClass("lnk_bn");
                }
                else {
                    $("#bnPartnerWing").css({ "display": "none" });
                }
            } else {
                $("#bnPartnerWing").css({ "display": "none" });
            }
        } catch (e) { }
    }
    function closeWindow_HeaderPid() {
        var todayDate = new Date();
        setCookieOneDay("HeaderPid_pop2", "OK", 24 - todayDate.getHours()); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#divYes24SCMEvent").hide();
    }
    function closeWindow__Mania_BookClub_pop() {
        var todayDate = new Date();
        setCookieOneDay("yes24_Mania_bookclub_pop", "OK", 24 - todayDate.getHours()); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#divYes24BookClubEvent_Mania").hide();
    }
</script>
<script src="https://image.yes24.com/static/common/frontCommon.js?v=20260624"></script>
    <!-- 광고 스크립트 - 공통 -->
    <!-- #include virtual="/Scripts/AdScript_Header.htm"-->
    <script async src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>



<script>
    var HTTP_URL = 'https://www.yes24.com';
    var PAYMENT_HTTP_URL = 'https://ssl.yes24.com/';
    var PAYMENT_API_URL = 'https://sslapi.yes24.com';
    var IMG_HOST_SYS = 'https://image.yes24.com';
    var YES_CART_AJAX_URL = '/Product/Content/AjaxPage/Cart/Cart'
    var SARAK_URL = 'https://sarak.yes24.com';
    var SARAK_API_URL = 'https://sarak-api.yes24.com';
    var FRONT_API_URL = 'https://frontapi.yes24.com';

    var ZIP_CD = '07237';
    var ZIP_SEQ = '001';
    var BU_MNG_NO = '1156011000100150015031131';
    var memRecentZipCd = '07237';
</script>


    <script src="https://image.yes24.com/sysimage/Contents/Scripts/m/ui/clipboard.min.js?v=20260624"></script>
    <script src="/Product/Scripts/yes24common.js?v=20251223"></script>
    <script src="/Product/Scripts/Yes24.Product.Common-1.0.js?v=20260723"></script>
        <script src="/Product/Scripts/YES24.Common-1.6.js?v=20260723"></script>
        <script src="/Product/Scripts/Goods/orderPayment-3.0.js?v=20260723"></script>
        <script src="https://image.yes24.com/static/common/notificationPopup.js?v=20260720a"></script>
    <script src="https://image.yes24.com/static/logging/brazeSDK.js?v=20260714"></script>
    <script src="https://image.yes24.com/static/logging/brazeHelper.js?v=20260714" defer></script>
    <script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20260714"></script>
    <script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20260714"></script>
    <script src="https://image.yes24.com/static/common/addon.js?v=20260204" charset="UTF-8"></script>

        <!-- Google Tag Manager -->
        <script>
            (function (w, d, s, l, i) {
                w[l] = w[l] || []; w[l].push({
                    'gtm.start':
                        new Date().getTime(), event: 'gtm.js'
                }); var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                        'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
        </script>
        <!-- End Google Tag Manager -->


    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/yesUI/layout/pcBase.css?v=20260323'>
    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/yesUI/search/search.css?v=20250818'>


</head>
<body>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
    <dl id="yesSkip"><dt>콘텐츠 바로가기</dt><dd><a href="#wrapperContent">본문 바로가기</a></dd></dl>
    <hr />
    <div id="yesWrap" class="">

        <script>
    var _ISADULT = "";
    var url = location.href;
    var reUrl = url.toLowerCase();
    var isWelcomePage = "False";
    var IsMania = 'False';
    var regQPop = false;
    var regBpop = false;
    var showHCPop = false;
</script>

<div id="yesHeaderArea" style="">
    <!-- ########## TOPBANNER 영역 시작 ########## -->
    <section>
        <div id="upperBnWrap" style="display:none;">
            <div id="upperBnRoll">
                <div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#d0ffb4"><a href="https://event.yes24.com/onlyApp" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0720_topbn_480x50_L_01.png" width="480" height="50" alt="도서앱"></a></div>
		<div class="upperBnSetRgt" style="background-color:#bfd0ff"><a href="https://event.yes24.com/yesbenefit" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0720_topbn_480x50_R_01.png" width="480" height="50" alt="혜택모음"></a></div>
	</div>
</div>
                <div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#feffb4"><a href="https://event.yes24.com/kidsreview/2026" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0720_topbn_480x50_L_02.png" width="480" height="50" alt="젊은작가"></a></div>
		<div class="upperBnSetRgt" style="background-color:#dab5ff"><a href="https://event.yes24.com/yesbenefit" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0720_topbn_480x50_R_01.png" width="480" height="50" alt="혜택모음"></a></div>
	</div>
</div>
                <div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#c3f4ff"><a href="https://event.yes24.com/template?EventNo=273472" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0720_topbn_480x50_L_03.png" width="480" height="50" alt="리딩런"></a></div>
		<div class="upperBnSetRgt" style="background-color:#78f2fd"><a href="https://event.yes24.com/yesbenefit" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0720_topbn_480x50_R_01.png" width="480" height="50" alt="혜택모음"></a></div>
	</div>
</div>
            </div>
            <div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
        </div>
    </section>
    <!-- ########## TOPBANNER 영역 끝 ########## -->
    <!-- ########## HEADER 영역 시작 ########## -->
    <div id="yHeader" class="">
    <h1>
        <a class="logo" href="https://www.yes24.com/main/default.aspx" onclick="setWcode('001_004');">
        <svg role="img" aria-label="YES24" type="image/svg+xml"><image src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" width="200" height="103" alt="YES24"></image></svg>
</a>

    </h1>
    <div id="yHeaderWrap">
        <!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
        <div class="yHeaderTop">
            <h2 class="yBlind">YES24 카테고리 리스트</h2>
            <ul class="cateLi" id="ulCategoryList">
            <li class="cate001 ">
                <a title="국내도서" href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" >
                    <em class="txt">국내도서</em>                </a>
            </li>
            <li class="cate002 ">
                <a title="외국도서" href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002" onclick="setWcode('001_002_002')" >
                    <em class="txt">외국도서</em>                </a>
            </li>
            <li class="cate018 ">
                <a title="중고샵" href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" >
                    <em class="txt">중고샵</em>                </a>
            </li>
            <li class="cate017 ">
                <a title="eBook" href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')" >
                    <em class="txt">eBook</em>                </a>
            </li>
            <li class="cateCrC ">
                <a title="크레마클럽" href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')" >
                    <em class="txt">크레마클럽</em>                </a>
            </li>
            <li class="cate003 ">
                <a title="CD/LP" href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" >
                    <em class="txt">CD/LP</em>                </a>
            </li>
            <li class="cate004 ">
                <a title="DVD/BD" href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" >
                    <em class="txt">DVD/BD</em>                </a>
            </li>
            <li class="cate006 ">
                <a title="문구/GIFT" href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" >
                    <em class="txt"><u>문구</u>/GIFT</em>                </a>
            </li>
            <li class="cateENT ">
                <a title="티켓" href="https://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank">

###HTML에서 데이터 추출하기 : BeautifulSoup

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(r.text, 'html.parser')

In [ ]:
#태그 위치 찾기 : find() 메서드
#첫 번째 매개변수 = 찾을 태그 이름을 지정 / attrs 매개변수 =  찾으려는 태그의 속성을 딕셔너리로 지정
prd_link = soup.find('a', attrs={'class':'gd_name'})

In [ ]:
print(prd_link)

<a class="gd_name" href="/product/goods/104089399" onclick="wiseLogV2('S', '101_005_003_001', ''); setGoodsClickExtraCodeHub('032', '9791189467302', '104089399', '0',this);">모국어는 차라리 침묵</a>

In [ ]:
#prd_link를 딕셔너리처럼 사용해 태그 안의 속성을 참조할 수 있음
print(prd_link['href'])

/product/goods/104089399

In [ ]:
#도서 상세 페이지 HTML 가져오기, requests.get()함수
url = 'http://www.yes24.com'+prd_link['href']
r = requests.get(url)

In [ ]:
#r을 사용해 가져온 HTML 출력
print(r.text)

<!DOCTYPE html>
<html lang="ko">
<head>
        <link rel="canonical" href="https://www.yes24.com/product/goods/104089399">
            <link rel="alternate" media="only screen and (max-width: 640px)" href="https://m.yes24.com/goods/detail/104089399">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta http-equiv="Accept-CH" content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" />
    <meta http-equiv="Accept-CH-Lifetime" content="86400" />
    <meta name="referrer" content="unsafe-url" />
    <meta name="viewport" content="width=1170" />
    <title>모국어는 차라리 침묵 | 목정원 | 아침달 - 예스24</title>
    <meta name="title" content="모국어는 차라리 침묵" />
        <meta name="author" content="목정원 저" />
    <meta name="description" content="모국어는 차라리 침묵. “슬픔을 아는 아름다움만큼 가치 있는 것은 없으니까요.”사라지는 것들이 남긴 흔적을 더듬는 목소리공연예술이론가 목정원의 비평 에세이공연예술이론가 목정원의 산문집 『모국어는 차라리 침묵』이 아침달에서 출간됐다. 목정원이 2013년부터 프랑..." />
    <meta name="keywords" content="룸펜레터에소개된책,목정원 산문, 아침달,1189467305,9791189467302" />
        <meta property="og:title" content="모국어는 차라리 침묵 | 목정원 | 아침달 - 예스24" />
            <meta property="og:type" content="book" />
            <meta property="og:url" content="https://www.yes24.com/product/goods/104089399" />
            <meta property="og:image" content="https://image.yes24.com/goods/104089399/xl" />
                    <meta property="og:site_name" content="예스24" />
            <meta property="og:description" content="“슬픔을 아는 아름다움만큼 가치 있는 것은 없으니까요.”사라지는 것들이 남긴 흔적을 더듬는 목소리공연예술이론가 목정원의 비평 에세이공연예술이론가 목정원의 산문집 『모국어는 차라리 침묵』이 아침달에서 출간됐다. 목정원이 2013년부터 프랑스에서 6년, 한국에서 ..." />
            <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="https://www.yes24.com/product/goods/104089399" />
        <meta name="twitter:title" content="모국어는 차라리 침묵 | 목정원 | 아침달 - 예스24" />
        <meta name="twitter:description" content="“슬픔을 아는 아름다움만큼 가치 있는 것은 없으니까요.”사라지는 것들이 남긴 흔적을 더듬는 목소리공연예술이론가 목정원의 비평 에세이공연예술이론가 목정원의 산문집 『모국어는 차라리 침묵』이 아침달에서 출간됐다. 목정원이 2013년부터 프랑스에서 6년, 한국에서 ..." />
        <meta name="twitter:image" content="https://image.yes24.com/goods/104089399/xl" />
        <meta property="books:isbn" content="9791189467302" />
        <meta property="books:rating:value" content="9.5" />
        <meta property="books:rating:scale" content="10" />
        <meta property="books:rating:normalized_value" content="0" />
            <link title="YES24" rel="search" type="application/opensearchdescription+xml" href="//www.yes24.com/OpensearchDescription.xml">






<script src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20250613"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20260701"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20260701"></script>
<script src="https://www.yes24.com/Javascript/util.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/yes_header.js?v=20260630"></script>
<script src="https://www.yes24.com/Javascript/hiveSlide.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20260630"></script>
<script src="https://www.yes24.com/Javascript/recentviewgoods.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/bulletSearch.js?v=20260630"></script>
<script src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20250613"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20250613"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20260630"></script>
    <script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.js?v=20260630"></script>
    <script src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20250613"></script>
    <link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20260630" charset=&quot;euc-kr&quot; />
    <link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20260630" />
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
<![endif]-->
<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" type="image/x-icon" rel="shortcut icon" />
<script src="https://www.yes24.com/Javascript/Common.js?v=20260624"></script>
<script src="https://www.yes24.com/Javascript/headerSetting.js?v=20260630"></script>
<script src="https://image.yes24.com/static/logging/clickstream.min.js?v=20260630"></script>
<script>
    var YesData = new function () {
        var _HTTP_URL = "https://www.yes24.com";
        var _NOW_HTTP_URL = "https://www.yes24.com";
        var _BLOG_URL = "https://blog.yes24.com";
        var _IMG_HOST_IMG = "https://image.yes24.com";
        var _IsWelcomePage = "False";
        var _MEM_AGE = 0;
        var _PID = "";
        var _FRONT_API_URL = "https://frontapi.yes24.com";
        var _ParenerInfomagion = {};
        var _IsdevServer = "False";
        var _IsHttps = "True";

        this.HTTP_URL = function () { return _HTTP_URL; }
        this.NOW_HTTP_URL = function () { return _NOW_HTTP_URL; }
        this.BLOG_URL = function () { return _BLOG_URL; }
        this.IMG_HOST_IMG = function () { return _IMG_HOST_IMG; }
        this.IsWelcomePage = function () { return _IsWelcomePage; }
        this.MEM_AGE = function () { return _MEM_AGE; }
        this.PID = function () { return _PID; }
        this.FRONT_API_URL = function() {return _FRONT_API_URL;}
        this.ParenerInfomagion = function () { return _ParenerInfomagion; }
        this.IsdevServer = function () { return _IsdevServer; }
        this.IsHttps = function () { return _IsHttps; }
    }

    var PC_HTTPS_URL = "https://www.yes24.com";
    var bnSkyAdArray = new Array();                 //AD 스카이스크래퍼용
    var HeaderDisplay = "";
    var isMania = "N";
    var recentViewGoods = new RecentViewGoods();    //최근본 상품
    var SearchBarRenderingEnable = true;            //광고창을 계속 불러올지 여부
    var USERNO = "";
    var IS_NATIVE_APPS = false;
    var is_debug = Boolean(0);
    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
    var IsScExpDate = scToday > scExpDate ? false : true;

    // 브레이즈 위한 설정 값
    var TUSERNO = '';
    var isUnder14 = 'False';
    function activeQuickSubmenu(row) {
        var $row = $(row),
            submenuId = $row.attr('data-submenu-id'),
            $submenu = $("#" + submenuId);
        $("#quickCate > li").removeClass("on");
        $submenu.css("display", "block");
        $row.parent().addClass("on");
        if (!quickChkWide) {
            if ((document.compatMode === "CSS1Compat") || (navigator.appName != 'Microsoft Internet Explorer')) {
                $("#quickCateWrap .quickCateLiWrap").css("overflow", "hidden");
                $("#quickCateWrap .quickCateLiWrap").stop().animate({ width: "664px" }, 200, "easeInCubic", function () {
                    if ($('#quickCateWrap').css("display") == "none") {
                        $(this).css("width", "auto");
                    }
                });
            } else {
                $("#quickCateWrap .quickCateLiWrap").css("width", "564px");
            }
            quickChkWide = true;
        }
    }
    function deactiveQuickSubmenu(row) {
        var $row = $(row),
            submenuId = $row.attr('data-submenu-id'),
            $submenu = $("#" + submenuId);
        $submenu.css("display", "none");
        $row.parent().removeClass("on");
    }
    function hideUpperBn() {
        setWcode('001_001');
        var todayDate = new Date();
        setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#upperBnWrap").css("display", "none");
    }
    // 검색어 입력창에 포커스 시
    function SearchBarRenderingEnableSet(enable) {
        //광고 제거
        SearchBarRenderingEnable = enable;
        $("#ulSchScopeOpt").hide();
    }
    // 검색어 입력창 광고 노출
    function fnSearchBarRendering() {
        var seardtext = $('#hdSearchBarText').val();
        var bannerLink = $("#hdSearchBarLink").val();
        $('#query').val(seardtext);
        $('#query').addClass("iptTxt iptTxtAd");
        $('#keywordAd').val(bannerLink);
    }
    //검색창 선택 시
    function showLatestSearchList() {
        SearchBarRenderingEnableSet(false);
        if (String($("input#query").val()).length == 0) {
            try {
                srchHistory.show();
            } catch (e) { }
            $("#suggestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#latestSearchList").show();
        } else {
            BulletSearchRenewal.InitBulletSearch();
            showSuggestSearchList();
        }
    }
    //검색창 포커스 아웃
    function blurSearchBar() {
        var queryValue = $("#query").val();
        if (queryValue == "" || queryValue == null) {
            if (location.href.toLowerCase().indexOf('/product/search') == -1) {
                fnSearchBarRendering();
                query_init = false;
            }
        }
    }
    function hideLatestSearchList() {
        $("#searchKeyLayer").hide();
        $("#latestSearchList").hide();
    }
    //추천검색어
    function showSuggestSearchList() {
        var domainVal = String($("#qdomain").val());
        if (domainVal != '티켓' && domainVal != '블로그' && domainVal != '채널예스' && domainVal != 'STORE' && domainVal != 'UsedGoods') {
            $("#latestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#suggestSearchList").show();
        } else {
            $("#suggestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#latestSearchList").show();
        }
    }
    function hideSuggestSearchList() {
        $("#searchKeyLayer").hide();
        $("#suggestSearchList").hide();
    }
    function closePartnerBn(close) {
        $("#bnPartnerWing").css({ "display": "none" });
        setCookie("Yes24_PartnerWingRightArea", "OK", 1);
    }
    function setCookiePartnerWingBn() {
        var name = "PartnerWingArea";
        var value = "OK";
        var expiredays = 1;
        var todayDate = new Date();
        todayDate.setDate(todayDate.getDate() + expiredays);
        document.cookie = name + "=" + escape(value) + "; path=/; expires=" + todayDate.toGMTString() + "; domain=.yes24.com;"
        closePartnerBn();
    }
    function OAS_RICHTest() {
        try {
            if (OAS_RICH.toString().indexOf("//adgirl.yes24.com/RealMedia/ads/Creatives/default/empty.gif") <= 0) {
                if (getCookie("Yes24_PartnerWingRightArea") != "OK") {
                    /*OAS_RICH("Right");*/
                    $("#bnPartnerWing a").eq(1).addClass("lnk_bn");
                }
                else {
                    $("#bnPartnerWing").css({ "display": "none" });
                }
            } else {
                $("#bnPartnerWing").css({ "display": "none" });
            }
        } catch (e) { }
    }
    function closeWindow_HeaderPid() {
        var todayDate = new Date();
        setCookieOneDay("HeaderPid_pop2", "OK", 24 - todayDate.getHours()); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#divYes24SCMEvent").hide();
    }
    function closeWindow__Mania_BookClub_pop() {
        var todayDate = new Date();
        setCookieOneDay("yes24_Mania_bookclub_pop", "OK", 24 - todayDate.getHours()); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#divYes24BookClubEvent_Mania").hide();
    }
</script>
<script src="https://image.yes24.com/static/common/frontCommon.js?v=20260624"></script>
    <!-- 광고 스크립트 - 공통 -->
    <!-- #include virtual="/Scripts/AdScript_Header.htm"-->
    <script async src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>



<script>
    var HTTP_URL = 'https://www.yes24.com';
    var PAYMENT_HTTP_URL = 'https://ssl.yes24.com/';
    var PAYMENT_API_URL = 'https://sslapi.yes24.com';
    var IMG_HOST_SYS = 'https://image.yes24.com';
    var YES_CART_AJAX_URL = '/Product/Content/AjaxPage/Cart/Cart'
    var SARAK_URL = 'https://sarak.yes24.com';
    var SARAK_API_URL = 'https://sarak-api.yes24.com';
    var FRONT_API_URL = 'https://frontapi.yes24.com';

    var ZIP_CD = '07237';
    var ZIP_SEQ = '001';
    var BU_MNG_NO = '1156011000100150015031131';
    var memRecentZipCd = '07237';
</script>


    <script src="https://image.yes24.com/sysimage/Contents/Scripts/m/ui/clipboard.min.js?v=20260624"></script>
    <script src="/Product/Scripts/yes24common.js?v=20251223"></script>
    <script src="/Product/Scripts/Yes24.Product.Common-1.0.js?v=20260723"></script>
        <script src="/Product/Scripts/YES24.Common-1.6.js?v=20260723"></script>
        <script src="/Product/Scripts/Goods/orderPayment-3.0.js?v=20260723"></script>
        <script src="https://image.yes24.com/static/common/notificationPopup.js?v=20260720a"></script>
    <script src="https://image.yes24.com/static/logging/brazeSDK.js?v=20260714"></script>
    <script src="https://image.yes24.com/static/logging/brazeHelper.js?v=20260714" defer></script>
    <script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20260714"></script>
    <script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20260714"></script>
    <script src="https://image.yes24.com/static/common/addon.js?v=20260204" charset="UTF-8"></script>




        <!-- Google Tag Manager -->
        <script>
            (function (w, d, s, l, i) {
                w[l] = w[l] || []; w[l].push({
                    'gtm.start':
                        new Date().getTime(), event: 'gtm.js'
                }); var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                        'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
        </script>
        <!-- End Google Tag Manager -->


    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/YESUI/detail/detail_2nd.css?v=20260602'>
    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/YESUI/detail/detail_class.css?v=20260602'>
    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/yesUI/yesLocation.css?v=20250818'>





<!-- 구조화된 데이터 -->
<script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": ["Book","Product"],
        "name": "모국어는 차라리 침묵",
        "image": {
            "@type": "ImageObject",
            "url": "https://image.yes24.com/goods/104089399/xl",
            "contentUrl": "https://image.yes24.com/goods/104089399/xl",
            "name": "모국어는 차라리 침묵",
            "creditText": "YES24 제공"
        },
        "description": "모국어는 차라리 침묵, “슬픔을 아는 아름다움만큼 가치 있는 것은 없으니까요.”사라지는 것들이 남긴 흔적을 더듬는 목소리공연예술이론가 목정원의 비평 에세이공연예술이론가 목정원의 산문집 『모국어는 차라리 침묵』이 아침달에서 출간됐다. 목정원이 2013년부터 프랑...",
        "genre": ["에세이","예술 에세이"],
        "keywords": "모국어는차라리침묵, 룸펜레터에소개된책, 목정원 산문, 아침달",
        "isbn": "9791189467302",
        "sku": "104089399",
        "bookFormat": "https://schema.org/Hardcover",
        "datePublished": "2021-10-15",
        "numberOfPages": 188,
            "inLanguage": "ko-KR",
        "url": "https://www.yes24.com/product/goods/104089399",
    "aggregateRating": {
          "@type": "AggregateRating",
          "ratingValue": 9.5,
          "reviewCount": 100,
          "bestRating": 10.0,
          "worstRating": 0.0
        },
    "author": {"@type":"Person","@id":"https://www.yes24.com/product/author/362513","url":"https://www.yes24.com/product/author/362513","name":"목정원"},"creditText": "목정원 저",        "publisher": {
            "@type":"Organization",
            "name":"아침달"
        },
            "offers": {
            "@type": "Offer",
            "price": 16740,
            "priceCurrency": "KRW",
            "availability": "https://schema.org/InStock",
            "url": "https://www.yes24.com/product/goods/104089399",
            "itemCondition": "https://schema.org/NewCondition",
            "seller": {
                "@type": "Organization",
                "name": "YES24"
            }

        },
        "workExample": [{
            "@type": "Book",
            "name": "모국어는 차라리 침묵",
            "bookFormat": "https://schema.org/EBook",
            "isbn": "9791189467463",
            "inLanguage": "ko-KR",
            "url": "https://www.yes24.com/product/goods/109903601"
            }]


    }
</script>

</head>
<body>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
    <dl id="yesSkip"><dt>콘텐츠 바로가기</dt><dd><a href="#wrapperContent">본문 바로가기</a></dd></dl>
    <hr />
    <div id="yesWrap" class="">

        <script>
    var _ISADULT = "";
    var url = location.href;
    var reUrl = url.toLowerCase();
    var isWelcomePage = "False";
    var IsMania = 'False';
    var regQPop = false;
    var regBpop = false;
    var showHCPop = false;
</script>

<div id="yesHeaderArea" style="">
    <!-- ########## TOPBANNER 영역 시작 ########## -->
    <section>
        <div id="upperBnWrap" style="display:none;">
            <div id="upperBnRoll">
                <div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#b3deff"><a href="https://event.yes24.com/onlyApp" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0430_topbn_480x50_L_01.png" width="480" height="50" alt="도서앱"></a></div>
		<div class="upperBnSetRgt" style="background-color:#ccf7d1"><a href="https://event.yes24.com/present?eventNo=269155" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0430_topbn_480x50_R_01.png" width="480" height="50" alt="우양산"></a></div>
	</div>
</div>


            </div>
            <div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
        </div>
    </section>
    <!-- ########## TOPBANNER 영역 끝 ########## -->
    <!-- ########## HEADER 영역 시작 ########## -->
    <div id="yHeader" class="">
    <h1>
        <a class="logo" href="https://www.yes24.com/main/default.aspx" onclick="setWcode('001_004');">

In [ ]:
soup = BeautifulSoup(r.text, 'html.parser')
prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
print(prd_detail)

<div class="gd_infoSet infoSet_noLine" id="infoset_specific">
<div class="tm_infoSet">
<h4 class="tit_txt">품목정보</h4>
</div>
<div class="infoSetCont_wrap">
<div class="yesTb">
<table class="tb_nor tb_vertical" summary="품목정보 국내도서, 외국도서 " width="100%">
<caption>품목정보</caption>
<colgroup>
<col width="170"/>
<col width="*"/>
</colgroup>
<tbody class="b_size">
<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2021년 10월 15일</td>
</tr>
<tr>
<th class="txt" scope="row">판형</th>
<td class="txt lastCol">
                                    양장
                                    <a class="bgYUI ico_comm ico_help" href="javascript:void(0);" onclick="showGoodsDetailPopup('bookBinding',this,{cock:true,mask:false,pWidth:640});" title="도서 제본방식 안내">도서 제본방식 안내</a>
</td>
</tr>
<tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">188쪽 | 312g | 127*200*15mm</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9791189467302</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">1189467305</td>
</tr>
</tbody>
</table>
</div>
</div>
<script type="text/javascript">
        if ($("#infoset_specific table tbody tr").length == 0) {
            $("#infoset_specific").remove();
        }
    </script>
</div>

In [ ]:
#테이블 태그를 리스트로 가져오기, find_all() 메서드
prd_tr_list = prd_detail.find_all('tr')
print(prd_tr_list)

[<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2021년 10월 15일</td>
</tr>, <tr>
<th class="txt" scope="row">판형</th>
<td class="txt lastCol">
                                    양장
                                    <a class="bgYUI ico_comm ico_help" href="javascript:void(0);" onclick="showGoodsDetailPopup('bookBinding',this,{cock:true,mask:false,pWidth:640});" title="도서 제본방식 안내">도서 제본방식 안내</a>
</td>
</tr>, <tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">188쪽 | 312g | 127*200*15mm</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9791189467302</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">1189467305</td>
</tr>]

####find()메서드 = 지정된 이름을 가진 첫 번째 태그를 찾음
####find_all()메서드 = 지정된 이름을 가진 모든 태그를 찾음
(find_all()메서드는 생략 가능)

In [ ]:
#태그 안의 텍스트 가져오기, get_text()메서드
for tr in prd_tr_list: #for문으로 prd_tr_list를 순회하면서 <th> 태그 안의 텍스트가 '쪽수, 무게, 크기'인지 검사함
  if tr.find('th').get_text() == '쪽수, 무게, 크기': #get_text() 메서드(태그 안에 텍스트를 반환) = <td> 안에 있는 텍스트를 가져옴
    page_td = tr.find('td').get_text()
    break

In [ ]:
print(page_td)

188쪽 | 312g | 127*200*15mm

In [ ]:
#split() 메서드 호출 = 공백을 기준으로 문자열을 나누어 리스트로 반환함
print(page_td.split()[0])

188쪽

##'전체 도서의 쪽수 구하기' - 총정리


1.   온라인 서점의 검색 결과 페이지 URL을 만듦
2.   requests.get()함수로 검색 결과 페이지의 HTML을 가져옴
3.   뷰티플수프로 HTML을 파싱함
4.   뷰티플수프의 find() 메서드로 a 태그를 찾아 상세 페이지 URL을 추출함
5.   requests.get() 함수로 다시 도서 상세 페이지의 HTML을 가져옴
6.   뷰티플수프로 HTML을 파싱함
7.   뷰티플수프의 find() 메서드로 '품목정보' div 태그를 찾음
8.   뷰티플수프의 find_all() 메서드로 '쪽수'가 들어있는 tr 태그를 찾음
9.   앞에서 찾은 테이블의 행에서 get_text() 메서드로 td 태그에 들어있는 '쪽수'를 가져옴

-> 이 작업을 구현한 get_page_cnt() 함수는 ISBN 정수 값을 받아 쪽수를 반환함

In [ ]:
def get_page_cnt(isbn):
  #Yes24 도서 검색 페이지 URL
  url = 'https://www.yes24.com/Product/Search?domain=ALL&query={}'

  #URL에 ISBN을 넣어 HTML을 가져옴
  r = requests.get(url.format(isbn))

  soup = BeautifulSoup(r.text, 'html.parser') #HTML 파싱

  # 검색 결과에서 해당 도서를 선택함
  prd_info = soup.find('a', attrs={'class':'gd_name'})
  if prd_info == None:
    return ''

  #도서 상세 페이지를 가져옴
  url = 'http://www.yes24.com'+prd_info['href']
  r = requests.get(url)
  soup = BeautifulSoup(r.text, 'html.parser')

  #품목정보 <div>를 선택
  prd_detail = soup.find('div', attrs={'id':'infoset_specific'})

  #테이블에 있는 <tr> 태그를 가져옴
  prd_tr_list = prd_detail.find_all('tr')

  #쪽수가 들어 있는 <th>를 찾아 <td>에 담긴 값을 반환함
  for tr in prd_tr_list:
    if tr.find('th').get_text() == '쪽수, 무게, 크기':
      return tr.find('td').get_text().split()[0]
  return ''

In [ ]:
get_page_cnt(9791189467302)

'188쪽'

In [ ]:
#데이터프레임 행 혹은 열에 함수 적용하기, apply() 메서드
top10_books = books.head(10)

In [ ]:
def get_page_cnt2(row): #데이터프레임의 한 행을 받아 get_page_cnt() 함수를 사용해 쪽수 구하는 함수를 만듦
  isbn = row['isbn13']
  return get_page_cnt(isbn)

In [ ]:
page_count = top10_books.apply(get_page_cnt2, axis = 1) # apply()메서드의 첫 번째 매개변수=실행할 함수 & axis = 1 행에 함수를 적용
print(page_count) # get_page_cnt2()함수의 결괏값은 page_count 변수에 판다스 시리즈 객체로 저장됨

0    188쪽
1    488쪽
2    224쪽
3    192쪽
4    208쪽
5    300쪽
6    224쪽
7    208쪽
8    108쪽
9    272쪽
dtype: object

####람다 함수(lambda)
-> 람다 함수는 함수 이름 없이 한 줄로 쓰는 함수임

In [ ]:
#람다 함수 활용
page_count = top10_books.apply(lambda row: get_page_cnt(row['isbn13']), axis=1)

In [ ]:
print(page_count)

0    188쪽
1    488쪽
2    224쪽
3    192쪽
4    208쪽
5    300쪽
6    224쪽
7    208쪽
8    108쪽
9    272쪽
dtype: object

In [ ]:
#page_count 시리즈 객체에 이름 지정해주기(시리즈 객체에 name 속성을 사용하면 이름을 간단하게 지정할 수 있음)
page_count.name = 'page_count'
print(page_count)

0    188쪽
1    488쪽
2    224쪽
3    192쪽
4    208쪽
5    300쪽
6    224쪽
7    208쪽
8    108쪽
9    272쪽
Name: page_count, dtype: object

In [ ]:
#데이터프레임과 시리즈 합치기, merge()함수
#두 객체의 인덱스를 기준으로 합칠 경우 left_index와 right_index 매개변수를 True로 지정함
top10_with_page_count = pd.merge(top10_books, page_count, left_index=True, right_index=True)
top10_with_page_count

,no,ranking,bookname,authors,publisher,publication_year,isbn13,page_count
0,1,1,모국어는 차라리 침묵 :목정원 산문,지은이: 목정원,아침달,2021,9791189467302,188쪽
1,2,2,디자인 컨셉 사전 :죽은 콘텐츠도 살리는 크리에이터의 말,테오 잉글리스 지음 ;이희수 옮김,윌북,2025,9791155818503,488쪽
2,3,3,당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임,글: 모데스토 가르시아 ;번역: 엄지영,중앙일보에스,2022,9788927812975,224쪽
3,4,3,다른 방식으로 보기,존 버거 [지음] ;최민 옮김,열화당,2012,9788930104272,192쪽
4,5,3,"디자인 구구단 =디자인이 필요한 순간, '툭' 튀어나오는 디자인 공식 /9 basi...",지은이: 에이핫,길벗,2024,9791140714063,208쪽
5,6,3,"열심히 대충 쓰는 사람 :브로콜리너마저 덕원의 가사, 노래, 글을 짓는 마음가짐",윤덕원 지음,세미콜론,2025,9791194087755,300쪽
6,7,7,"드라마 만드는 사람 :찾고, 조율하고, 완성하는 기획 PD의 세계",송진선 지음,RHK(알에이치코리아),2025,9788925572970,224쪽
7,8,7,당신은 사건 현장에 있습니다 :일러스트 한 장으로 즐기는 추리 게임,글: 모데스토 가르시아 ;번역: 엄지영,중앙일보에스,2025,9788927813361,208쪽
8,9,7,창작수업,지은이: 변영주,창비,2024,9788936480264,108쪽
9,10,7,나의 문구 여행기 :좋아하는 것을 좋아하는 용기에 대하여,지은이: 문경연 ;사진: 한진희,뜨인돌,2020,9788958077466,272쪽

#### 웹 스크래핑 할 때 주의할 점


1.   웹사이트에서 스크래핑을 허락하였는지 확인하기
-대부분의 웹사이트는 이를 명시한 robots.txt 파일을 가지고 있음
2.   HTML 태그를 특정할 수 있는지 확인하기
-태그를 특정할 수 없다면 웹 스크래핑으로 데이터를 가져오는 데 어려움이 있음


-> 웹 스크래핑은 최후의 수단으로 사용하는 것이 좋음