### 데이터 정제
-> 데이터에서 손상되거나 부정확한 부분을 수정하고, 불필요한 데이터를 삭제하거나 불완전한 값을 교체하는 등의 작업을 말함.

- 데이터 정제는 데이터를 분석 목적에 맞게 변환하는 '데이터 랭글링' 또는 '데이터 먼징'의 일부로 수행될 수 있음.

#####열 삭제하기
#####-loc 메서드와 불리언 배열, 원소별 비교, drop() 메서드, inplace 매개변수, dropna() 메서드

In [ ]:
import gdown
gdown.download('http://drive.google.com/uc?id=1Y0IeakjUU9nHy1QIIgekql6PNepzAT4-', 'ns_202604.csv',quiet=False)

Downloading...
From: http://drive.google.com/uc?id=1Y0IeakjUU9nHy1QIIgekql6PNepzAT4-
To: /content/ns_202604.csv
100%|██████████| 78.0M/78.0M [00:01<00:00, 56.7MB/s]

'ns_202604.csv'

In [ ]:
import pandas as pd
ns_df = pd.read_csv('ns_202604.csv', low_memory=False)
ns_df.head()
#Unnamed:13 = CSV 파일 각 라인의 끝에 콤마가 있어서 판다스가 자동으로 추가한 열(불필요하므로 삭제하는게 좋음)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30,NaN
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30,NaN
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30,NaN
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30,NaN
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,NaN,1,0,2026-04-30,NaN

In [ ]:
#loc 메서드에 슬라이싱 사용해서 새로운 데이터프레임 만들기
ns_book = ns_df.loc[:,'번호':'등록일자']
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#데이터프레임 열 이름이 저장된 columns 속성 확인하기
#columns 속성 = 판다스의 Index 클래스 객체임. 이 객체의 원소는 파이썬의 리스트처럼 숫자 인덱스로 참조가
print(ns_df.columns)
print('-----------------------------------------------------------------------------------------------------')
print(ns_df.columns[0])

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '부가기호', '권',
       '주제분류번호', '도서권수', '대출건수', '등록일자', 'Unnamed: 13'],
      dtype='object')
-----------------------------------------------------------------------------------------------------
번호

##-원소별 비교
##### 판다스 배열 성격의 객체는 어떤 값과 비교할 때 자동으로 배열에 있는 모든 원소와 하나씩 비교해줌.

##-데이터프레임 중간에 있는 열 빼고 나머지를 선택하고 싶을 때
#####불리언 배열이나 drop() 메서드 사용하기

In [ ]:
#데이터프레임 중간에 있는 열을 삭제하고 싶을 때, 불리언 배열
ns_df.columns != '부가기호'
#반환된 결과는 '넘파이 배열'임

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True])

In [ ]:
#얻은 불리언 배열 값을 selected_columns 변수에 저장하고 판다스 데이터프레임의 loc 메서드에 전달하면 True인 열의 행만 선택가능
selected_columns = ns_df.columns != '부가기호'
ns_book = ns_df.loc[:, selected_columns]
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,1,0,2026-04-30,NaN
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,1,0,2026-04-30,NaN
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,1,0,2026-04-30,NaN
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,1,0,2026-04-30,NaN
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,1,0,2026-04-30,NaN

In [ ]:
#drop() 메서드 = 판다스에서는 데이터프레임의 행이나 열을 삭제하는 drop() 메서드를 제공함
#첫 번째 매개변수에 삭제하려는 열 이름을 전달하고 axis 매개변수를 1로 지정함
ns_book = ns_df.drop('Unnamed: 13', axis=1) #Unnamed: 13 열 삭제
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#'부가기호'와 'Unnamed: 13' 열 함께 제거(리스트 형식 사용)
ns_book = ns_df.drop(['부가기호','Unnamed: 13'], axis =1)
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,1,0,2026-04-30
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,1,0,2026-04-30
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#inplace() = True -> 현재 선택한 데이터프레임을 바로 수정할 수 있음.
#'주제분류번호'삭제하기
ns_book.drop('주제분류번호',axis=1,inplace=True)
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,1,0,2026-04-30
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,1,0,2026-04-30
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,1,0,2026-04-30

In [ ]:
#dropna() 메서드 -> 기본적으로 NaN이 하나 이상 포함된 행이나 열을 삭제함
#how 매개변수를 'all'로 지정하면 모든값이 NaN인 열이 삭제됨
ns_book=ns_df.dropna(axis=1)
ns_book.head()

   번호           ISBN  도서권수  대출건수        등록일자
0   1  9791124226087     1     0  2026-04-30
1   2  9791168343764     1     0  2026-04-30
2   3  9791158792541     1     0  2026-04-30
3   4  9791175772656     1     0  2026-04-30
4   5  9791175772663     1     0  2026-04-30

In [ ]:
ns_book=ns_df.dropna(axis=1,how='all')
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,NaN,1,0,2026-04-30

#####행 삭제하기
#####-loc 메서드, drop() 메서드, dropna() 메서드, 불리언 배열을 [] 연산자에 전달

In [ ]:
#drop() 메서드 활용
ns_book2 = ns_book.drop([0,1]) #인덱스 0부터 1까지 2개 행을 선택함
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,NaN,1,0,2026-04-30
5,6,파이로매니악 3,이우혁 지음,반타,2026,9791175772670,NaN,NaN,NaN,NaN,1,0,2026-04-30
6,7,약속의 세대,백온유 지음,문학동네,2026,9791141615819,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#[]연산자와 슬라이싱
#[]연산자에 슬라이싱이나 불리언 배열을 전달하면 행을 선택함
ns_book2 = ns_book[2:] # 0,1을 제외한 행 출력
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,NaN,1,0,2026-04-30
5,6,파이로매니악 3,이우혁 지음,반타,2026,9791175772670,NaN,NaN,NaN,NaN,1,0,2026-04-30
6,7,약속의 세대,백온유 지음,문학동네,2026,9791141615819,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#[]연산자에 슬라이싱을 사용하면 loc 메서드에 슬라이싱을 사용하는 것과는 다르게 마지막 인덱스를 포함하지 않음
ns_book2 = ns_book[0:2]
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#[]연산자와 불리언 배열
selected_rows = ns_df['출판사'] == '한빛미디어' #출판사가 '한빛미디어'인 행만 선택
ns_book2 = ns_book[selected_rows]
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
28,29,바이브 코더를 위한 최소한의 AI/IT 지식,"클리커 지음, 이희영 옮김",한빛미디어,2026,9791175790544,NaN,NaN,NaN,NaN,1,0,2026-04-30
29,30,콘텐츠 디자인 with 나노 바나나,홍순성 지음,한빛미디어,2026,9791175790469,NaN,NaN,NaN,NaN,1,0,2026-04-30
540,541,(회사에서 바로 통하는) 실무 엑셀 파워포인트 워드 & 한글,"전미진,이화진,신면철 [공]지음",한빛미디어,2025,9791169214117,NaN,1,NaN,005.5,1,1,2026-04-14
570,571,"한눈에 보는 AI 반도체 산업 :GPU부터 HBM, 파운드리, 패키징, 데이터센터까...",MrTrigger 지음,한빛미디어,2026,9791175790407,NaN,0,NaN,569.4,1,1,2026-04-14
610,611,"오픈클로 with GPT, 제미나이, 클로드",강민혁 지음,한빛미디어,2026,9791175790315,NaN,NaN,NaN,004.73,1,1,2026-04-10

In [ ]:
#loc 메서드에 불리언 배열을 사용하여 행을 선택하는 것도 가능
ns_book2 = ns_book.loc[selected_rows,:] #슬라이싱을 사용해 전체 열을 선택한다는 것을 명시적으로 표현할 수도 있지만, ':'를 생략해서 사용해도 됨
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
28,29,바이브 코더를 위한 최소한의 AI/IT 지식,"클리커 지음, 이희영 옮김",한빛미디어,2026,9791175790544,NaN,NaN,NaN,NaN,1,0,2026-04-30
29,30,콘텐츠 디자인 with 나노 바나나,홍순성 지음,한빛미디어,2026,9791175790469,NaN,NaN,NaN,NaN,1,0,2026-04-30
540,541,(회사에서 바로 통하는) 실무 엑셀 파워포인트 워드 & 한글,"전미진,이화진,신면철 [공]지음",한빛미디어,2025,9791169214117,NaN,1,NaN,005.5,1,1,2026-04-14
570,571,"한눈에 보는 AI 반도체 산업 :GPU부터 HBM, 파운드리, 패키징, 데이터센터까...",MrTrigger 지음,한빛미디어,2026,9791175790407,NaN,0,NaN,569.4,1,1,2026-04-14
610,611,"오픈클로 with GPT, 제미나이, 클로드",강민혁 지음,한빛미디어,2026,9791175790315,NaN,NaN,NaN,004.73,1,1,2026-04-10

In [ ]:
#대출건수가 1,000 이하인 행을 삭제하고 싶을 때 -> []연산자에 조건 넣어주기
ns_book2 = ns_book[ns_book['대출건수'] > 1000]
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
160554,160555,"사피엔스 :유인원에서 사이보그까지, 인간 역사의 대담하고 위대한 질문",유발 하라리 지음 ;조현욱 옮김,김영사,2016,9788934972464,NaN,NaN,NaN,909,30,1947,2016-04-22
410476,410477,해커스 토익:Listening,David Cho 지음,해커스어학연구소,2005,9788990700148,NaN,1,NaN,740.77,29,1066,2005-02-01

#####중복된 행 찾기
#####-duplicated() 메서드 = 데이터프레임에 있는 모든 열을 기준으로 중복된 행을 찾음

In [ ]:
#duplicated() 메서드 -> 처음을 제외한 나머지 중복된 행을 True로 표시, 그 외 중복되지 않은 나머지 행들은 False로 표시
sum(ns_book.duplicated()) #sum() 함수를 함께 사용하면 True를 1로 인식하기 때문에 중복된 행의 개수를 셀 수 있음

0

In [ ]:
#일부 열을 기준으로 중복된 행을 찾으려면 subset 매개변수에 기준열을 나열함
sum(ns_book.duplicated(subset=['도서명','저자','ISBN']))

21630

In [ ]:
#어떤 데이터가 중복되었는지 확인하기 = keep 매개변수(False로 지정하여 중복된 모든 행을 True로 표시한 불리언 배열을 반환)
dup_rows = ns_book.duplicated(subset=['도서명','저자','ISBN'], keep=False)
ns_book3 = ns_book[dup_rows]
ns_book3.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
6,7,약속의 세대,백온유 지음,문학동네,2026,9791141615819,NaN,NaN,NaN,NaN,1,0,2026-04-30
36,37,어머니의 유산,이해수 지음,창조문예사,2026,9791191797916,NaN,NaN,NaN,NaN,1,0,2026-04-29
48,49,펫폿 :이은후 장편소설,이은후 지음,자음과모음,2025,9788954473392,NaN,NaN,NaN,813.7,1,0,2026-04-29
175,176,나의 완벽한 장례식,조현선 지음,책읽어주는남자,2026,9791124038192,NaN,0,NaN,813.7,1,0,2026-04-27
209,210,나도 피자,강수린 지음,북멘토,2025,9788963196596,NaN,7,NaN,813.8,1,1,2026-04-24

##### 그룹별로 모으기
#####-groupby() 메서드

In [ ]:
#groupby() 메서드의 by 매개변수에는 행을 합칠 때 기준이 되는 열을 지정함
count_df = ns_book[['도서명','저자','ISBN','권','대출건수']]

#groupby() 메서드는 기본적으로 by 매개변수에 지정된 열에 NaN이 포함되어 있으면 해당 해을 삭제함.
#이를 막기 위해 dropna 매개변수를 False로 지정함
group_df = count_df.groupby(by=['도서명','저자','ISBN','권'], dropna=False)

#sum() 메서드 = 대출건수를 하나로 합쳐야하므로 sum() 메서드를 활용
loan_count = group_df.sum()

loan_count = count_df.groupby(by=['도서명', '저자', 'ISBN','권'], dropna=False).sum()
#head() 메서드로 데이터프레임을 출력하면, 기준인 인덱스 열이 굵은 글시로 표시됨
loan_count.head()

                                                                                           대출건수
도서명                                            저자                       ISBN          권
(꼭 필요한 것부터 쉽게 배우는) 자신만만 블로그 차근차근 배우기           김상현 지음                   9788955025637 NaN    38
(대한민국이 한 번도 경험하지 못한) 가장 강력한 주식 시장이 온다          홍성학 지음                   9791188726806 NaN    13
(맨처음 배우는) 세상의 직업                               엘레오노라 바르소티 글 ·그림 ;김태은 옮김 9788992924146 NaN    10
(생초보도 쉽게 따라 할 수 있는 경매) 경매 교과서                  설마 안정일 지음                9788965023005 NaN    44
(영잘원 리스닝과 패턴 영어의 절묘한 만남으로 태어난 ) 리스닝 ABC : 입문편  JD Kim 지음                9788993466089 NaN     5

#####원본 데이터 업데이트하기


1.   duplicated() 메서드로 중복된 행을 True로 표시한 불리언 배열을 만듦.
2.   1번에서 구한 불리언 배열을 반전시켜서 중복되지 않은 고유한 행을 True로 표시

-반전시킬 때는 판다스의 '~'연산자를 사용함

3.   2번에서 구한 불리언 배열을 사용해 원본 배열에서 고유한 행만 선택

-copy() 메서드로 ns_book3 데이터프레임을 만듦

In [ ]:
dup_rows=ns_book.duplicated(subset=['도서명','저자','ISBN','권']) # 1번

unique_rows = ~dup_rows # 2번
ns_book3 = ns_book[unique_rows].copy() # 3번

In [ ]:
# ns_book3에 중복된 행이 없는지 duplicated() 메서드로 확인하기
sum(ns_book3.duplicated(subset=['도서명','저자','ISBN','권']))

0

In [ ]:
#원본 데이터프레임 인덱스 설정하기(ns_book3의 인덱스를 loan_count 데이터프레임의 인덱스와 동일하게 만듦)
#set_index() -> 지정한 열을 인덱스로 설정할 때 사용
#inplace 매개변수를 True로 지정해 새로운 df을 반환하지 않고 ns_book3 df을 수정
ns_book3.set_index(['도서명','저자','ISBN','권'], inplace=True)
ns_book3.head()

,,,,번호,출판사,발행년도,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자
도서명,저자,ISBN,권,,,,,,,,,
지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,9791124226087,NaN,1,갈매나무,2026,NaN,NaN,NaN,1,0,2026-04-30
흉담,전건우 지음,9791168343764,NaN,2,래빗홀,2026,NaN,NaN,NaN,1,0,2026-04-30
아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",9791158792541,NaN,3,북로드,2026,NaN,NaN,NaN,1,0,2026-04-30
파이로매니악 1,이우혁 지음,9791175772656,NaN,4,반타,2026,NaN,NaN,NaN,1,0,2026-04-30
파이로매니악 2,이우혁 지음,9791175772663,NaN,5,반타,2026,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#업데이트하기 = update() 메서드
ns_book3.update(loan_count)
ns_book3.head()

/tmp/ipykernel_1981/3675334744.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  ns_book3.update(loan_count)

,,,,번호,출판사,발행년도,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자
도서명,저자,ISBN,권,,,,,,,,,
지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,9791124226087,NaN,1,갈매나무,2026,NaN,NaN,NaN,1,0,2026-04-30
흉담,전건우 지음,9791168343764,NaN,2,래빗홀,2026,NaN,NaN,NaN,1,0,2026-04-30
아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",9791158792541,NaN,3,북로드,2026,NaN,NaN,NaN,1,0,2026-04-30
파이로매니악 1,이우혁 지음,9791175772656,NaN,4,반타,2026,NaN,NaN,NaN,1,0,2026-04-30
파이로매니악 2,이우혁 지음,9791175772663,NaN,5,반타,2026,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#업데이트가 되었다면 인덱스 열을 해제함 = reset_index() 메서드로 df 인덱스를 재설정가능
ns_book4 = ns_book3.reset_index()
ns_book4.head()

,도서명,저자,ISBN,권,번호,출판사,발행년도,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자
0,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,9791124226087,NaN,1,갈매나무,2026,NaN,NaN,NaN,1,0,2026-04-30
1,흉담,전건우 지음,9791168343764,NaN,2,래빗홀,2026,NaN,NaN,NaN,1,0,2026-04-30
2,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",9791158792541,NaN,3,북로드,2026,NaN,NaN,NaN,1,0,2026-04-30
3,파이로매니악 1,이우혁 지음,9791175772656,NaN,4,반타,2026,NaN,NaN,NaN,1,0,2026-04-30
4,파이로매니악 2,이우혁 지음,9791175772663,NaN,5,반타,2026,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#원본 데이터인 ns_book에서 대출건수가 100회 이상인 책의 개수 세기
sum(ns_book['대출건수']>100)

2756

In [ ]:
#ns_book4에서 대출건수가 100회 이상인 책의 개수 세기
#늘어난 이유 : 중복된 도서의 대출건수를 합쳤기 때문
sum(ns_book4['대출건수']>100)

3181

In [ ]:
#원래 열 이름대로 맞추기 = []연산자에 원래 df의 열 값을 전달
ns_book4 = ns_book4[ns_book.columns]
ns_book4.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#저장
ns_book4.to_csv('ns_book4.csv', index = False)

In [ ]:
#일괄 처리 함수, data_cleaning() 함수
def data_cleaning(filename):
  """
  남산 도서관 장서 CSV 데이터 전처리 함수
  :param filename: CSV 파일 이름
  """

  #파일을 데이터프레임으로 읽습니다.
  ns_df = pd.read_csv(filename, low_memory=False)
  #NaN인 열을 삭제합니다.
  ns_book = ns_df.dropna(axis=1, how='all')
  #대출건수를 합치기 위해 필요한 행만 추출하여 count_df 데이터프레임을 만듭니다.
  count_df = ns_book[['도서명','저자','ISBN','권','대출건수']]
  #도서명, 저자, ISBN, 권을 기준으로 대출건수 groupby합니다.
  loan_count = count_df.groupby(by=['도서명','저자','ISBN','권'], dropna=False).sum()

  #원본 데이터프레임에서 중복된 행을 제외하고 고유한 행만 추출하여 복사합니다.
  dup_rows = ns_book.duplicated(subset=['도서명','저자','ISBN','권'])
  unique_rows = ~dup_rows
  ns_book3 = ns_book[unique_rows].copy()
  #도서명, 저자, ISBN, 권을 인덱스로 설정합니다.
  ns_book3.set_index(['도서명','저자','ISBN','권'], inplace=True)
  #loan_count에 저장된 누적 대출건수를 업데이트합니다.
  ns_book3.update(loan_count)
  #인덱스를 재설정합니다.
  ns_book4=ns_book3.reset_index()
  #원본 데이터프레임의 열 순서로 변경합니다.
  ns_book4 = ns_book4[ns_book.columns]
  return ns_book4

In [ ]:
#함수가 제대로 동작하는지 확인
new_ns_book4 = data_cleaning('ns_202604.csv')
#다른 데이터프레임을 비교할 때, equals() 메서드 사용
ns_book4.equals(new_ns_book4)

/tmp/ipykernel_1981/1493050727.py:24: PerformanceWarning: indexing past lexsort depth may impact performance.
  ns_book3.update(loan_count)

True