In [ ]:
import gdown
gdown.download('http://drive.google.com/uc?id=1Se4X-MC5G27TtoSQ1-DKjWS2r1De2uIT','ns_book4.csv',quiet=False)

Downloading...
From: http://drive.google.com/uc?id=1Se4X-MC5G27TtoSQ1-DKjWS2r1De2uIT
To: /content/ns_book4.csv
100%|██████████| 63.1M/63.1M [00:00<00:00, 90.6MB/s]

'ns_book4.csv'

####데이터프레임 정보 요약 확인하기

In [ ]:
import pandas as pd
ns_book4 = pd.read_csv('ns_book4.csv', low_memory=False)
ns_book4.head() #처음 5개 행 출력

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30
2,3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30
3,4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#info() 메서드 = 열마다 NaN이 아닌 값이 몇 개나 있는지 확인할 수 있음, 데이터프레임 정보를 요약해서 출력해줌
ns_book4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 446613 entries, 0 to 446612
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   번호       446613 non-null  int64
 1   도서명      446213 non-null  object
 2   저자       446406 non-null  object
 3   출판사      440933 non-null  object
 4   발행년도     446573 non-null  object
 5   ISBN     446613 non-null  object
 6   세트 ISBN  26064 non-null   float64
 7   부가기호     326878 non-null  object
 8   권        69141 non-null   object
 9   주제분류번호   423629 non-null  object
 10  도서권수     446613 non-null  int64
 11  대출건수     446613 non-null  int64
 12  등록일자     446613 non-null  object
dtypes: float64(1), int64(3), object(9)
memory usage: 44.3+ MB

In [ ]:
#memory_usage 매개변수에 'deep' 옵션 지정 = 정확한 메모리 사용량을 얻을 수 있음
ns_book4.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 446613 entries, 0 to 446612
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   번호       446613 non-null  int64
 1   도서명      446213 non-null  object
 2   저자       446406 non-null  object
 3   출판사      440933 non-null  object
 4   발행년도     446573 non-null  object
 5   ISBN     446613 non-null  object
 6   세트 ISBN  26064 non-null   float64
 7   부가기호     326878 non-null  object
 8   권        69141 non-null   object
 9   주제분류번호   423629 non-null  object
 10  도서권수     446613 non-null  int64
 11  대출건수     446613 non-null  int64
 12  등록일자     446613 non-null  object
dtypes: float64(1), int64(3), object(9)
memory usage: 258.8 MB

####누락된 값 처리하기

In [ ]:
#isna() 메서드 = 누락된 값을 직접 카운트 가능, 각 행이 비어 있는지를 나타내는 불리언 배열(T/F)을 반환함
#sum() 메서드를 이어서 호출하면 불리언 배열의 True 개수로 비어 있는 행 개수를 얻을 수 있음
ns_book4.isna().sum()

번호              0
도서명           400
저자            207
출판사          5680
발행년도           40
ISBN            0
세트 ISBN    420549
부가기호       119735
권          377472
주제분류번호      22984
도서권수            0
대출건수            0
등록일자            0
dtype: int64

In [ ]:
#isna() 메서드 <-> notna() 메서드 = 누락되지 않은 값을 확인할 때 사용
ns_book4.notna().sum()

번호         446613
도서명        446213
저자         446406
출판사        440933
발행년도       446573
ISBN       446613
세트 ISBN     26064
부가기호       326878
권           69141
주제분류번호     423629
도서권수       446613
대출건수       446613
등록일자       446613
dtype: int64

In [ ]:
#누락된 값으로 표시하기 : None과 np.nan
#판다스 데이터프레임에서는 정수를 저장하는 열에 파이썬의 None을 입력하면 누락된 값으로 인식함

# - '도서권수'열에 있는 첫 번째 행 값을 None으로 바꾼 후 '도서권수'열에 isna()메서드를 적용해 누락된 값 세어보기
ns_book4.loc[0, '도서권수']=None #loc 메서드 복습 : 데이터프레임 행과 열 선택
ns_book4['도서권수'].isna().sum()

np.int64(1)

In [ ]:
ns_book4.head(2)
#'도서권수'가 NaN으로 바뀌고 두 번째 행 값이 1->1.0으로 바뀐 이유
# - 판다스는 NaN을 특별한 실수 값으로 저장함. NaN을 표시하기 위해 float64로 바뀜.

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,NaN,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1.0,0,2026-04-30

In [ ]:
#데이터 타입 지정하기 = astype() 메서드 -> 기본적으로 새로운 데이터프레임을 반환함
#매개변수를 {열 이름:데이터 타입} 형식의 딕셔너리로 전달
ns_book4.loc[0, '도서권수'] = 1
ns_book4 = ns_book4.astype({'도서권수':'int64', '대출건수':'int64'})
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
# 문자열을 저장할 수 있는 열에 None을 입력하면 어떨까?
ns_book4.loc[0,'부가기호']=None
ns_book4.head(2)

#판다스는 NaN이라는 값을 따로 가지고 있지 않기에 그대로 None으로 표시됨

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,None,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#np.nan = NaN을 표시하기 위해선 넘파이 패키지에 있는 np.nan을 사용해야함
#np.nan은 숫자와 문자열 데이터 타입에 상관없이 NaN 표시
import numpy as np
ns_book4.loc[0, '부가기호']=np.nan
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30

#### 누락된 값 바꾸기 : loc() 메서드, fillna() 메서드, replace() 메서드

In [ ]:
#누락된 값 바꾸기(1) : loc() 메서드
# -loc() 메서드 : 누락된 값을 원하는 값으로 바꿀 수 있음
# isna() 메서드로 NaN을 가리키는 불리언 배열을 만든 후 loc 메서드에 전달

#누락된 값을 찾아 불리언 배열로 반환
set_isbn_na_rows = ns_book4['세트 ISBN'].isna()

#누락된 값을 빈 문자열로 바꿈/ loc = 행과 열을 이름으로 찾아서 선택하거나 수정하는 역할
ns_book4.loc[set_isbn_na_rows, '세트 ISBN']='' #해석: set_isbn_na_rows가 True인 행에서 '세트 ISBN'을 선택
#누락된 값이 몇 개인지 셈
ns_book4['세트 ISBN'].isna().sum()

#결과
#-세트 ISBN 열의 NaN을 모두 빈 문자열로 바꾸었기 때문에 누락된 행의 개수는 0임

/tmp/ipykernel_691/3759763926.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  ns_book4.loc[set_isbn_na_rows, '세트 ISBN']=''

np.int64(0)

In [ ]:
#누락된 값 바꾸기(2) : fillna() 메서드
#fillna() 메서드에 원하는 값을 전달하면 NaN을 대체할 수 있음
#기본적으로 새로운 데이터프레임을 반환하므로 fillna() 메서드에 이어서 isna() 메서드를 연결하면 NaN의 개수를 셀 수 있음
ns_book4.fillna('없음').isna().sum()

#결과
# - NaN이 모두 '없음' 문자열로 바뀌어 NaN 개수를 세면 0이 출력됨

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [ ]:
#특정 열만 선택해서 NaN을 바꿀 수도 있음
#특정 열을 선택한 후 fillna() 메서드를 적용하면 열 이름 없이 개수만 있는 판다스 시리즈 객체로 반환됨
ns_book4['부가기호'].fillna('없음').isna().sum()

np.int64(0)

In [ ]:
#부가기호 열의 NaN을 바꾸면서 전체 데이터프레임을 반환하려면 열 이름과 바꾸려는 값으로 이루어진 딕셔너리를 전달하면 됨
ns_book4.fillna({'부가기호':'없음'}).isna().sum()

#cf)fillna() 메서드의 method 매개변수에 'ffill'을 지정하면 누락된 값 이전에 등장하는 유효한 값으로 현재 누락된 값을 채움
#   method 매개변수에 'bfill'을 지정하면 누락된 값 이후에 등장하는 유효한 값으로 현재 누락된 값을 채움

번호              0
도서명           400
저자            207
출판사          5680
발행년도           40
ISBN            0
세트 ISBN         0
부가기호            0
권          377472
주제분류번호      22984
도서권수            0
대출건수            0
등록일자            0
dtype: int64

In [ ]:
#누락된 값 바꾸기(3) : replace() 메서드
#replace() 메서드는 NaN포함 어떤 값도 바꿀 수 있는 편리한 메서드임, 기본적으로 새로운 DF을 반환하여 여러 메서드를 연이어 쓸 수 있음

#1. 바꾸려는 값이 하나일 때 = replace(원래 값, 바꾸려는 값)
ns_book4.replace(np.nan, '없음').isna().sum()

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [ ]:
#2. 바꾸려는 값이 여러 개일 때 = replace([원래 값1, 원래 값2], [새로운 값1, 새로운 값2]), 리스트/딕셔너리 형태 둘 다 가능
#리스트 형식
ns_book4.replace([np.nan, '2026'],['없음', '26']).head(2)

#딕셔너리 형식
ns_book4.replace({np.nan: '없음', '2026': '26'}).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,26,9791124226087,,없음,없음,없음,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,26,9791168343764,,없음,없음,없음,1,0,2026-04-30

In [ ]:
#3. 열 마다 다른 값으로 바꿀 때 = replace({열 이름: 원래 값}, 새로운 값), 딕셔너리/중첩 딕셔너리 형태 둘 다 가능
#딕셔너리 형식
ns_book4.replace({'부가기호':np.nan}, '없음').head(2)

#중첩된 딕셔너리 형식
ns_book4.replace({'부가기호':{np.nan:'없음'}, '발행년도':{'2026':'26'}}).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,26,9791124226087,,없음,NaN,NaN,1,0,2026-04-30
1,2,흉담,전건우 지음,래빗홀,26,9791168343764,,없음,NaN,NaN,1,0,2026-04-30

#### replace() 메서드에 정규 표현식 사용하기
###정규표현식(=정규식)이란?
- 문자열 패턴을 찾아서 대체하기 위한 규칙의 모음

In [ ]:
#숫자 찾기 : \d
#ex) 2026 -> \d\d\d\d
#그룹으로 묶기 \d\d(\d\d) -> \1,\2로 그룹을 나타냄
#regex = True -> 정규 표현식을 사용한다는 의미
#r = 원시 문자열을 만듦
ns_book4.replace({'발행년도':{r'\d\d(\d\d)':r'\1'}}, regex=True)[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,스카이다이빙:문경민 장편소설,문경민 지음,문학동네,26,9791141615123,,0,NaN,813.7,1,0,2026-04-29
101,102,일곱 개의 초록 :황보나 연작소설,황보나 지음,문학동네,25,9791141613723,,0,NaN,813.7,1,0,2026-04-29

In [ ]:
#정규 표현식이 반복될 때는 중괄호를 사용하여 개수를 지정할 수 있음
#\d{2} = \d\d (같은 표현)
ns_book4.replace({'발행년도':{r'\d{2}(\d{2})':r'\1'}},regex=True)[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,스카이다이빙:문경민 장편소설,문경민 지음,문학동네,26,9791141615123,,0,NaN,813.7,1,0,2026-04-29
101,102,일곱 개의 초록 :황보나 연작소설,황보나 지음,문학동네,25,9791141613723,,0,NaN,813.7,1,0,2026-04-29

In [ ]:
#문자 찾기 : 마침표(.)
ns_book4.replace({'저자':{r'(.*)\s\(지은이\)(.*)\s\(옮긴이\)': r'\1\2'}, '발행년도': {r'\d{2}(\d{2})': r'\1'}}, regex=True)[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,스카이다이빙:문경민 장편소설,문경민 지음,문학동네,26,9791141615123,,0,NaN,813.7,1,0,2026-04-29
101,102,일곱 개의 초록 :황보나 연작소설,황보나 지음,문학동네,25,9791141613723,,0,NaN,813.7,1,0,2026-04-29

####잘못된 값 바꾸기

In [ ]:
#판다스 시리즈 객체는 str 속성 아래 다양한 문자열 처리 함수를 제공함
#contains() 메서드 = 시리즈나 인덱스에서 문자열 패턴을 포함하고 있는지 검사함
#contains() 메서드는 주어진 문자열이 포함된 모든 행을 찾음
ns_book4['발행년도'].str.contains('1988').sum()

454

In [ ]:
#'발행년도'에서 숫자가 아닌 문자를 포함하는 모든 행 찾기
# \D -> 숫자가 아닌 다른 모든 문자에 대응하는 표현
#na 매개변수를 True로 지정하여 연도가 누락된 행을 True로 표시

invalid_number = ns_book4['발행년도'].str.contains(r'\D', na=True)
print(invalid_number.sum())
ns_book4[invalid_number].head()

866

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
808,812,"어서 오세요, 남산 호텔로!",김여진 글,나무의말,NaN,9791198860545,,NaN,NaN,813.8,1,0,2026-04-09
8037,8266,전쟁에 동원된 남자들,"석미화 외 지음, 아카이브평화기억 기획",알록,NaN,9791198988126,,NaN,NaN,914.103,1,8,2025-07-18
8038,8267,인어의 발걸음,"리웨이징 지음, 심지연 옮김",복복서가,NaN,9791191114881,,NaN,NaN,823.7,1,4,2025-07-18
13512,13955,데이터 상속인,한상운 (지은이),문학동네,NaN,9791141601836,,NaN,NaN,813.7,1,2,2025-02-21
21679,22309,심플하게 산다,도미니크 로로 지음 ;김성희 옮김,바다출판사,2016(2024년 12쇄),9788955616477,,1,1,199.1,1,23,2024-06-20

In [ ]:
#정규 표현식을 사용하여 연도 앞과 뒤에 있는 문자 제외하기
ns_book5 = ns_book4.replace({'발행년도':r'.*(\d{4}).*'}, r'\1', regex=True)
ns_book5[invalid_number].head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
808,812,"어서 오세요, 남산 호텔로!",김여진 글,나무의말,NaN,9791198860545,,NaN,NaN,813.8,1,0,2026-04-09
8037,8266,전쟁에 동원된 남자들,"석미화 외 지음, 아카이브평화기억 기획",알록,NaN,9791198988126,,NaN,NaN,914.103,1,8,2025-07-18
8038,8267,인어의 발걸음,"리웨이징 지음, 심지연 옮김",복복서가,NaN,9791191114881,,NaN,NaN,823.7,1,4,2025-07-18
13512,13955,데이터 상속인,한상운 (지은이),문학동네,NaN,9791141601836,,NaN,NaN,813.7,1,2,2025-02-21
21679,22309,심플하게 산다,도미니크 로로 지음 ;김성희 옮김,바다출판사,2024,9788955616477,,1,1,199.1,1,23,2024-06-20

In [ ]:
#숫자 이외의 문자가 들어간 행의 개수와 데이터 재확인
unknown_year = ns_book5['발행년도'].str.contains(r'\D', na=True)
print(unknown_year.sum())
ns_book5[unknown_year].head()

95

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
808,812,"어서 오세요, 남산 호텔로!",김여진 글,나무의말,NaN,9791198860545,,NaN,NaN,813.8,1,0,2026-04-09
8037,8266,전쟁에 동원된 남자들,"석미화 외 지음, 아카이브평화기억 기획",알록,NaN,9791198988126,,NaN,NaN,914.103,1,8,2025-07-18
8038,8267,인어의 발걸음,"리웨이징 지음, 심지연 옮김",복복서가,NaN,9791191114881,,NaN,NaN,823.7,1,4,2025-07-18
13512,13955,데이터 상속인,한상운 (지은이),문학동네,NaN,9791141601836,,NaN,NaN,813.7,1,2,2025-02-21
33111,34341,"안락사, 죽음과 그 밖의 것들","아드리아노 페시나 지음, 박은호 옮김",가톨릭대학교출판부,NaN,9788971083611,,NaN,NaN,NaN,1,4,2023-06-16

In [ ]:
#어떻게 변환할지 알 수 없는 데이터들은 임의로 -1값으로 바꾼다음 astype() 메서드로 발행년도 열의 데이터 타입을 정수형인 int64로 변환
ns_book5.loc[unknown_year, '발행년도'] = '-1'
ns_book5 = ns_book5.astype({'발행년도': 'int64'})

In [ ]:
#gt() 메서드로 전달된 값보다 큰 값 찾기
ns_book5['발행년도'].gt(4000).sum()

np.int64(131)

In [ ]:
#서기로 바꾸기
dangun_yy_rows = ns_book5['발행년도'].gt(4000)
ns_book5.loc[dangun_yy_rows, '발행년도'] = ns_book5.loc[dangun_yy_rows,'발행년도']-2333

dangun_year = ns_book5['발행년도'].gt(4000)
print(dangun_year.sum())
ns_book5[dangun_year].head(2)

14

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
31483,32471,부자 아빠의 투자 가이드,"로버트 기요사키 지음, 박슬라 옮김",창비교육,5667,9791165702069,,NaN,NaN,NaN,1,31,2023-08-02
285510,299568,Modern art,[computer file],GROLIER,7611,9780717233243,,NaN,NaN,609.205,1,1,2009-05-07

In [ ]:
#모두 -1로 표시하기
ns_book5.loc[dangun_year,'발행년도'] = -1

In [ ]:
#연도가 작은 값도 확인하기
old_books = ns_book5['발행년도'].gt(0) & ns_book5['발행년도'].lt(1900)
ns_book5[old_books]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
6679,6863,지극히 사적인 일본,나리카와 아야 지음,틈새책방,530,9791188949755,,NaN,NaN,309.113,1,7,2025-08-21
6680,6864,관세전쟁,추동훈.이승주.강영연 지음,한즈미디어(한스미디어),512,9791194777106,,NaN,NaN,321.97,1,6,2025-08-21
6681,6865,한 번 배우면 평생 써먹는 ETF 투자법,윤타(윤영준) 지음,동양북스(동양문고),714,9791172101145,,NaN,NaN,327.856,1,10,2025-08-21
6682,6866,박곰희 연금 부자 수업,박곰희 지음,인플루엔셜(주),625,9791168342941,,NaN,NaN,327.8,1,13,2025-08-21
6683,6867,먼저 온 미래,장강명 지음,동아시아,626,9788962626605,,NaN,NaN,331.544,1,9,2025-08-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
133192,140142,정신 병리학의 문제들,지은이: 지그문트 프로이트 ;옮긴이: 황보석,열린책들,151,9788932905181,,9,10,185.5,1,7,2017-04-26
142185,149955,(최근 7년간) 중요 민법판례 :[2009년 1월~2016년 6월 중요 판례],이광섭 편저,법학사,163,9788962898651,,9,NaN,365,1,14,2016-09-27
210555,223417,(한·중·일) 밥상 문화 :대표음식으로 본 3국 문화비교,김경은 지음,이가서,132,9788958643012,,0,NaN,381.75,1,34,2013-02-19
257230,270909,책으로 뒤덮인 집의 비밀,N.E. 보드 지음 ;피터 퍼거슨 그림 ;김지현 옮김,개암나무,1015,9788992844413,,7,NaN,843,1,15,2010-08-18
349765,364411,(밝혀질)우리歷史,吳在城 著,黎民族史硏究會,1607,9788986892130,,0,NaN,911,1,8,2006-07-06

In [ ]:
#해당 도서도 -1로 설정하고 전체 행 개수 확인하기
ns_book5.loc[old_books, '발행년도'] = -1
ns_book5['발행년도'].eq(-1).sum()

np.int64(260)

####누락된 정보 채우기

In [ ]:
na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna()\
          |ns_book5['출판사'].isna() | ns_book5['발행년도'].eq(-1)
print(na_rows.sum())
ns_book5[na_rows].head(2)

6486

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
252,253,퍼트리샤 하이스미스:일기와 노트,"지음: 퍼트리샤 하이스미스 ;편집: 안나 폰 플란타 ;번역: 노지양,김은지",NaN,2025,9791190738354,,0,2,846,1,0,2026-04-20
254,255,퍼트리샤 하이스미스:일기와 노트,"지음: 퍼트리샤 하이스미스 ;편집: 안나 폰 플란타 ;번역: 노지양,김은지",NaN,2025,9791190738347,,0,1,846,1,0,2026-04-20

In [ ]:
#뷰티플수프를 사용해 값 채우기
import requests
from bs4 import BeautifulSoup

In [ ]:
def get_book_title(isbn):
  url = 'https://www.yes24.com/product/search?domain=ALL&query=%25EC%259A%25B0%25EB%25A6%25AC%25EA%25B0%2580%2520%25EB%25B9%259B%25EC%259D%2598%2520%25EC%2586%258D%25EB%258F%2584%25EB%25A1%259C%2520%25EA%25B0%2588%2520%25EC%2588%2598%2520%25EC%2597%2586%25EB%258B%25A4%25EB%25A9%25B4'
  r=requests.get(url.format(isbn))
  soup = BeautifulSoup(r.text, 'html.parser')

  title = soup.find('a', attrs={'class':'gd_name'}).get_text()

  return title

In [ ]:
get_book_title(9791191266054)

'우리가 빛의 속도로 갈 수 없다면'

In [ ]:
#저자, 출판사, 발행 연도를 추출하여 반환하는 함수 만들기
import re

def get_book_info(row):
  title = row['도서명']
  author = row['저자']
  pub = row['출판사']
  year = row['발행년도']

  url = 'https://www.yes24.com/product/search?domain=ALL&query=%25EC%259A%25B0%25EB%25A6%25AC%25EA%25B0%2580%2520%25EB%25B9%259B%25EC%259D%2598%2520%25EC%2586%258D%25EB%258F%2584%25EB%25A1%259C%2520%25EA%25B0%2588%2520%25EC%2588%2598%2520%25EC%2597%2586%25EB%258B%25A4%25EB%25A9%25B4'

  r=requests.get(url.format(row['ISBN']))
  soup = BeautifulSoup(r.text, 'html.parser')
  try:
    if pd.isna(title):
      title = soup.find('a', attrs={'class':'gd_name'}).get_text()

  except AttributeError:
    pass

  try:
    if pd.isna(author):
      authors = soup.find('span', attrs={'class':'info_auth'}).find_all('a')
      author_list = [auth.get_text() for auth in authors]
      author = ','.join(author_list)

  except AttributeError:
    pass

  try:
    if pd.isna(pub):
      pub = soup.find('span', attrs={'class':'info_pub'}).find('a').get_text()

  except AttributeError:
    pass

  try:
    if year == -1:
      year_str = soup.find('span', attrs={'class':'info_date'}).get_text()

      year = re.findall(r'\d{4}', year_str)[0]

  except AttributeError:
    pass

  return title, author, pub, year

In [ ]:
#누락된 값이 있었던 처음 두 개의 행에 get_book_info()함수 적용하기
#apply() 메서드는 기본적으로 반환된 값을 하나의 튜플로 만듦
#result_type 매개변수를 'expand'로 지정하여 반환된 값을 각기 다른 열로 만들 수 있음

updated_sample = ns_book5[na_rows].head(2).apply(get_book_info, axis=1, result_type = 'expand')
updated_sample

                     0                                          1   2     3
252  퍼트리샤 하이스미스:일기와 노트  지음: 퍼트리샤 하이스미스 ;편집: 안나 폰 플란타 ;번역: 노지양,김은지  허블  2025
254  퍼트리샤 하이스미스:일기와 노트  지음: 퍼트리샤 하이스미스 ;편집: 안나 폰 플란타 ;번역: 노지양,김은지  허블  2025

In [ ]:
#파일 새로 저장하기
gdown.download('https://drive.google.com/uc?id=1Tc_AhqAbmzTfBv_fUAqlQisvvnZkP7qJ','ns_book5_update.csv', quiet=False)

ns_book5_update = pd.read_csv('ns_book5_update.csv', index_col=0)
ns_book5_update.head()

Downloading...
From: https://drive.google.com/uc?id=1Tc_AhqAbmzTfBv_fUAqlQisvvnZkP7qJ
To: /content/ns_book5_update.csv
100%|██████████| 63.1M/63.1M [00:01<00:00, 57.0MB/s]
/tmp/ipykernel_691/815611635.py:3: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  ns_book5_update = pd.read_csv('ns_book5_update.csv', index_col=0)

,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
번호,,,,,,,,,,,,
1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,NaN,NaN,NaN,NaN,1,0,2026-04-30
2,흉담,전건우 지음,래빗홀,2026,9791168343764,NaN,NaN,NaN,NaN,1,0,2026-04-30
3,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,NaN,NaN,NaN,NaN,1,0,2026-04-30
4,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,NaN,NaN,NaN,NaN,1,0,2026-04-30
5,파이로매니악 2,이우혁 지음,반타,2026,9791175772663,NaN,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#누락된 행 확인하기
ns_book5.update(ns_book5_update)
na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna()| ns_book5['출판사'].isna()\
          | ns_book5['발행년도'].eq(-1)
print(na_rows.sum())

/tmp/ipykernel_691/3840955567.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2026 '2026' '2026' ... '1995' '1995' '1995']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  ns_book5.update(ns_book5_update)

262

In [ ]:
#dropna() 메서드에 열을 리스트로 저장 후 누락된 값이 있는 행 삭제 후 발행년도 열 값이 -1이 아닌 행만 선택하여 ns_book6 데이터프레임 생성하기
ns_book6 = ns_book5.dropna(subset=['도서명','저자','출판사'])
ns_book6 = ns_book6[ns_book6['발행년도']!= -1]
ns_book6.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,,NaN,NaN,NaN,1,0,2026-04-30
1,2,지도와 전쟁으로 다시 읽는 한중일 세계사,이동민 지음,갈매나무,2026,9791124226087,,NaN,NaN,NaN,1,0,2026-04-30
2,3,흉담,전건우 지음,래빗홀,2026,9791168343764,,NaN,NaN,NaN,1,0,2026-04-30
3,4,아름다움이 사람을 죽일 때,"미시마 유키오 지음, 심지애 옮김",북로드,2026,9791158792541,,NaN,NaN,NaN,1,0,2026-04-30
4,5,파이로매니악 1,이우혁 지음,반타,2026,9791175772656,,NaN,NaN,NaN,1,0,2026-04-30

In [ ]:
#저장
ns_book6.to_csv('ns_book6.csv', index=False)

#### 일괄 처리 함수

In [ ]:
def data_fixing(ns_book4):


#잘못된 값을 수정하거나 NaN을 채우는 함수
#:param ns_book4: data_cleaning()함수에서 전처리된 데이터프레임

#도서권수와 대출건수를 int64로 바꿈
ns_book4 = ns_book4.astype({'도서권수':'int64','대출건수':'int64'})
#NaN인 세트 ISBN을 빈 문자열로 바꿈
set_isbn_na_rows = ns_book4['세트 ISBN'].isna()
ns_book4.loc[set_isbn_na_rows, '세트 ISBN']=''
#발행년도 열에서 연도 네 자리를 추출하여 대체함. 나머지 발행년도는 -1로 바꿈
ns_book5 = ns_book4.replace({'발행년도':r'.*(\d{4}).*'}, r'\1', regex=True)
unknown_year = ns_book5['발행년도'].str.contains(r'\D', na=True)
ns_book5.loc[unknown_year, '발행년도'] = '-1'
#발행년도를 int32로 바꿈
ns_book5 = ns_book5.astype({'발행년도':'int32'})
#4000년 이상인 경우 2333년을 뺌
dangun_yy_rows = ns_book5['발행년도'].gt(4000)
ns_book5.loc[dangun_yy_rows, '발행년도'] = ns_book5.loc[dangun_yy_rows, '발행년도']-2222

#여전히 4000년 이상인 경우 -1로 바꿈
dangun_year = ns_book5['발행년도'].gt(4000)
ns_book5.loc[dangun_year, '발행년도'] = -1

#0~1900년 사이의 발행년도는 -1로 바꿈
old_books = ns_book5['발행년도'].gt(0) & ns_book5['발행년도'].lt(1900)
ns_book5.loc[old_books, '발행년도']= -1

#도서명, 저자, 출판사가 NaN이거나 발행년도가 -1인 행을 찾음
na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna()\
          |ns_book5['출판사'].isna() | ns_book5['발행년도'].eq(-1)

#Yes24 도서 상세 페이지에서 누락된 정보를 채움
updated_sample= ns_book5[na_rows].apply(get_book_info, axis =1, result_type = 'expand')
updated_sample.columns = ['도서명','저자','출판사','발행년도']
ns_book5.update(updated_sample)

#도서명, 저자, 출판사가 NaN이거나 발행년도가 -1인 행을 삭제함
ns_book6 = ns_book5.dropna(subset=['도서명','저자','출판사'])
ns_book6 = ns_book6[ns_book6['발행년도']!= -1]

IndentationError: expected an indented block after function definition on line 1 (3764362550.py, line 9)